-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_167_22_VITIS_LOOP_168_23_VITIS_LOOP_169_24 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer2_pool_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    layer2_pool_ce0 : OUT STD_LOGIC;
    layer2_pool_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    flat_ce0 : OUT STD_LOGIC;
    flat_we0 : OUT STD_LOGIC;
    flat_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_167_22_VITIS_LOOP_168_23_VITIS_LOOP_169_24 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_620 : STD_LOGIC_VECTOR (10 downto 0) := "11000100000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_70 : STD_LOGIC_VECTOR (7 downto 0) := "01110000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv11_70 : STD_LOGIC_VECTOR (10 downto 0) := "00001110000";
    constant ap_const_lv11_8 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln167_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln168_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln168_reg_507 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal and_ln167_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln167_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln170_3_fu_316_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal idx_1_cast_fu_422_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal f_fu_62 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln169_fu_321_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_f_load : STD_LOGIC_VECTOR (3 downto 0);
    signal idx_1_fu_66 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln170_fu_427_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal c_fu_70 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln168_2_fu_280_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (3 downto 0);
    signal idx_fu_74 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln168_3_fu_415_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvar_flatten155_fu_78 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln168_4_fu_333_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten155_load : STD_LOGIC_VECTOR (7 downto 0);
    signal r_fu_82 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln167_3_fu_208_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_r_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvars_iv189_fu_86 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln167_4_fu_395_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvar_flatten171_fu_90 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln167_2_fu_170_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten171_load : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln167_fu_188_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_224_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_216_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln170_fu_232_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln169_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln167_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln167_1_fu_200_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln168_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln168_fu_260_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln170_fu_236_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln170_1_fu_288_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln170_1_fu_292_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln168_1_fu_272_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_298_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln170_2_fu_306_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln170_2_fu_310_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln168_2_fu_327_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln167_1_fu_375_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln167_fu_381_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln168_1_fu_402_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln167_2_fu_388_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln168_fu_408_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_predict_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_predict_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    c_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln167_fu_164_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_70 <= select_ln168_2_fu_280_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_70 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    f_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln167_fu_164_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    f_fu_62 <= add_ln169_fu_321_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_62 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    idx_1_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    idx_1_fu_66 <= ap_const_lv11_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    idx_1_fu_66 <= add_ln170_fu_427_p2;
                end if;
            end if; 
        end if;
    end process;

    idx_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    idx_fu_74 <= ap_const_lv11_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    idx_fu_74 <= select_ln168_3_fu_415_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten155_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln167_fu_164_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten155_fu_78 <= select_ln168_4_fu_333_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten155_fu_78 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten171_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln167_fu_164_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten171_fu_90 <= add_ln167_2_fu_170_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten171_fu_90 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    indvars_iv189_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvars_iv189_fu_86 <= ap_const_lv11_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvars_iv189_fu_86 <= select_ln167_4_fu_395_p3;
                end if;
            end if; 
        end if;
    end process;

    r_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln167_fu_164_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    r_fu_82 <= select_ln167_3_fu_208_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_82 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln167_fu_164_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln167_reg_514 <= and_ln167_fu_254_p2;
                icmp_ln168_reg_507 <= icmp_ln168_fu_194_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln167_1_fu_375_p2 <= std_logic_vector(unsigned(indvars_iv189_fu_86) + unsigned(ap_const_lv11_70));
    add_ln167_2_fu_170_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten171_load) + unsigned(ap_const_lv11_1));
    add_ln167_fu_188_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r_load) + unsigned(ap_const_lv4_1));
    add_ln168_1_fu_402_p2 <= std_logic_vector(unsigned(select_ln167_fu_381_p3) + unsigned(ap_const_lv11_8));
    add_ln168_2_fu_327_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten155_load) + unsigned(ap_const_lv8_1));
    add_ln168_fu_260_p2 <= std_logic_vector(unsigned(select_ln167_1_fu_200_p3) + unsigned(ap_const_lv4_1));
    add_ln169_fu_321_p2 <= std_logic_vector(unsigned(select_ln168_1_fu_272_p3) + unsigned(ap_const_lv4_1));
    add_ln170_1_fu_292_p2 <= std_logic_vector(unsigned(sub_ln170_fu_236_p2) + unsigned(zext_ln170_1_fu_288_p1));
    add_ln170_2_fu_310_p2 <= std_logic_vector(unsigned(tmp_6_fu_298_p3) + unsigned(zext_ln170_2_fu_306_p1));
    add_ln170_fu_427_p2 <= std_logic_vector(unsigned(select_ln168_fu_408_p3) + unsigned(ap_const_lv11_1));
    and_ln167_fu_254_p2 <= (xor_ln167_fu_242_p2 and icmp_ln169_fu_248_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln167_fu_164_p2)
    begin
        if (((icmp_ln167_fu_164_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_70)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_70;
        end if; 
    end process;


    ap_sig_allocacmp_f_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, f_fu_62, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_f_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_f_load <= f_fu_62;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten155_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten155_fu_78)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten155_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten155_load <= indvar_flatten155_fu_78;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten171_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten171_fu_90)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten171_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten171_load <= indvar_flatten171_fu_90;
        end if; 
    end process;


    ap_sig_allocacmp_r_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, r_fu_82)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_r_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_r_load <= r_fu_82;
        end if; 
    end process;

    flat_address0 <= idx_1_cast_fu_422_p1(11 - 1 downto 0);

    flat_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            flat_ce0 <= ap_const_logic_1;
        else 
            flat_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    flat_d0 <= layer2_pool_q0;

    flat_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            flat_we0 <= ap_const_logic_1;
        else 
            flat_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln167_fu_164_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten171_load = ap_const_lv11_620) else "0";
    icmp_ln168_fu_194_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten155_load = ap_const_lv8_70) else "0";
    icmp_ln169_fu_248_p2 <= "1" when (ap_sig_allocacmp_f_load = ap_const_lv4_8) else "0";
    idx_1_cast_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln168_fu_408_p3),64));
    layer2_pool_address0 <= zext_ln170_3_fu_316_p1(11 - 1 downto 0);

    layer2_pool_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_pool_ce0 <= ap_const_logic_1;
        else 
            layer2_pool_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln168_fu_266_p2 <= (icmp_ln168_fu_194_p2 or and_ln167_fu_254_p2);
    select_ln167_1_fu_200_p3 <= 
        ap_const_lv4_0 when (icmp_ln168_fu_194_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln167_2_fu_388_p3 <= 
        add_ln167_1_fu_375_p2 when (icmp_ln168_reg_507(0) = '1') else 
        idx_1_fu_66;
    select_ln167_3_fu_208_p3 <= 
        add_ln167_fu_188_p2 when (icmp_ln168_fu_194_p2(0) = '1') else 
        ap_sig_allocacmp_r_load;
    select_ln167_4_fu_395_p3 <= 
        add_ln167_1_fu_375_p2 when (icmp_ln168_reg_507(0) = '1') else 
        indvars_iv189_fu_86;
    select_ln167_fu_381_p3 <= 
        add_ln167_1_fu_375_p2 when (icmp_ln168_reg_507(0) = '1') else 
        idx_fu_74;
    select_ln168_1_fu_272_p3 <= 
        ap_const_lv4_0 when (or_ln168_fu_266_p2(0) = '1') else 
        ap_sig_allocacmp_f_load;
    select_ln168_2_fu_280_p3 <= 
        add_ln168_fu_260_p2 when (and_ln167_fu_254_p2(0) = '1') else 
        select_ln167_1_fu_200_p3;
    select_ln168_3_fu_415_p3 <= 
        add_ln168_1_fu_402_p2 when (and_ln167_reg_514(0) = '1') else 
        select_ln167_fu_381_p3;
    select_ln168_4_fu_333_p3 <= 
        ap_const_lv8_1 when (icmp_ln168_fu_194_p2(0) = '1') else 
        add_ln168_2_fu_327_p2;
    select_ln168_fu_408_p3 <= 
        add_ln168_1_fu_402_p2 when (and_ln167_reg_514(0) = '1') else 
        select_ln167_2_fu_388_p3;
    sub_ln170_fu_236_p2 <= std_logic_vector(unsigned(tmp_s_fu_216_p3) - unsigned(zext_ln170_fu_232_p1));
    tmp_5_fu_224_p3 <= (select_ln167_3_fu_208_p3 & ap_const_lv1_0);
    tmp_6_fu_298_p3 <= (add_ln170_1_fu_292_p2 & ap_const_lv3_0);
    tmp_s_fu_216_p3 <= (select_ln167_3_fu_208_p3 & ap_const_lv4_0);
    xor_ln167_fu_242_p2 <= (icmp_ln168_fu_194_p2 xor ap_const_lv1_1);
    zext_ln170_1_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln168_2_fu_280_p3),8));
    zext_ln170_2_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln168_1_fu_272_p3),11));
    zext_ln170_3_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln170_2_fu_310_p2),64));
    zext_ln170_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_224_p3),8));
end behav;
