-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_103_6_VITIS_LOOP_104_7_VITIS_LOOP_105_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer1_pool_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    layer1_pool_ce0 : OUT STD_LOGIC;
    layer1_pool_we0 : OUT STD_LOGIC;
    layer1_pool_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    layer1_conv_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    layer1_conv_ce0 : OUT STD_LOGIC;
    layer1_conv_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    layer1_conv_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    layer1_conv_ce1 : OUT STD_LOGIC;
    layer1_conv_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    layer1_conv_address2 : OUT STD_LOGIC_VECTOR (13 downto 0);
    layer1_conv_ce2 : OUT STD_LOGIC;
    layer1_conv_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    layer1_conv_address3 : OUT STD_LOGIC_VECTOR (13 downto 0);
    layer1_conv_ce3 : OUT STD_LOGIC;
    layer1_conv_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_865_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_865_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_865_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_865_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_865_p_ce : OUT STD_LOGIC;
    grp_fu_869_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_869_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_869_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_869_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_869_p_ce : OUT STD_LOGIC;
    grp_fu_873_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_873_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_873_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_873_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_873_p_ce : OUT STD_LOGIC;
    grp_fu_877_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_877_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_877_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_877_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_877_p_ce : OUT STD_LOGIC );
end;


architecture behav of cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_103_6_VITIS_LOOP_104_7_VITIS_LOOP_105_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_CE6E6B28 : STD_LOGIC_VECTOR (31 downto 0) := "11001110011011100110101100101000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv12_F04 : STD_LOGIC_VECTOR (11 downto 0) := "111100000100";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv10_3C1 : STD_LOGIC_VECTOR (9 downto 0) := "1111000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln103_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln113_1_fu_480_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030_pp0_iter2_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030_pp0_iter3_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030_pp0_iter4_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030_pp0_iter5_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030_pp0_iter6_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln113_1_reg_1030_pp0_iter7_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal layer1_conv_load_reg_1055 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_1_reg_1062 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_1_reg_1062_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_2_reg_1069 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_2_reg_1069_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_2_reg_1069_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_2_reg_1069_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_3_reg_1076 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_3_reg_1076_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_3_reg_1076_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_3_reg_1076_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_3_reg_1076_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_conv_load_3_reg_1076_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_fu_714_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_reg_1083 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_1_fu_804_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_1_reg_1090 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_1_reg_1090_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_2_fu_892_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_2_reg_1097 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln110_2_reg_1097_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln109_5_fu_522_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln109_6_fu_551_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln109_8_fu_590_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln109_10_fu_623_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln113_2_fu_898_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_90 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln105_fu_628_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_1_fu_94 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln104_1_fu_346_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten15_fu_98 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln104_4_fu_640_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal f_fu_102 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln103_1_fu_276_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten39_fu_106 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln103_1_fu_241_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_29_fu_221_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln104_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln103_fu_256_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_fu_229_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln105_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln103_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_fu_268_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln103_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln104_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln104_fu_326_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_358_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln113_fu_354_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_mid_fu_372_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln103_2_fu_292_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln104_2_fu_380_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_13_fu_388_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_14_fu_400_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln109_fu_396_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln109_1_fu_408_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal p_mid113_fu_418_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln103_3_fu_300_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln104_3_fu_424_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_fu_432_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_16_fu_444_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln109_2_fu_440_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln109_3_fu_452_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal select_ln104_fu_338_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln113_fu_366_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln113_1_fu_462_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln113_fu_466_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_33_fu_472_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln103_1_fu_288_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_34_fu_486_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln109_fu_412_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln109_4_fu_494_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln109_fu_498_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal tmp_40_cast_fu_504_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_35_fu_514_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln109_1_fu_456_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln109_1_fu_527_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal tmp_44_cast_fu_533_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_36_fu_543_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal or_ln109_fu_556_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln109_fu_562_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln109_7_fu_566_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln109_2_fu_570_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_37_fu_576_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln103_fu_284_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln109_3_fu_584_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln109_1_fu_595_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln109_9_fu_599_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln109_4_fu_603_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_38_fu_609_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln109_5_fu_617_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln104_1_fu_634_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal bitcast_ln110_fu_673_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_676_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_fu_686_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_1_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln110_1_fu_722_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln110_2_fu_739_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_725_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_1_fu_735_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_3_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_2_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_742_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_2_fu_752_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_5_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_4_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_1_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_2_fu_786_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_1_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_2_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln110_3_fu_810_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln110_4_fu_827_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_813_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_3_fu_823_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_7_fu_850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_6_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_830_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_4_fu_840_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_9_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_8_fu_862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_3_fu_856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_4_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_3_fu_880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_4_fu_886_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln110_5_fu_902_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln110_6_fu_919_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_905_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_5_fu_915_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_11_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_10_fu_936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_922_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln110_6_fu_932_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln110_13_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln110_12_fu_954_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_5_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln110_6_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_5_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln110_6_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_predict_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cnn_predict_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_predict_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    c_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_90 <= ap_const_lv5_0;
                elsif (((icmp_ln103_fu_235_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    c_fu_90 <= add_ln105_fu_628_p2;
                end if;
            end if; 
        end if;
    end process;

    f_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_102 <= ap_const_lv3_0;
                elsif (((icmp_ln103_fu_235_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    f_fu_102 <= select_ln103_1_fu_276_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten15_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten15_fu_98 <= ap_const_lv10_0;
                elsif (((icmp_ln103_fu_235_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten15_fu_98 <= select_ln104_4_fu_640_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten39_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten39_fu_106 <= ap_const_lv12_0;
                elsif (((icmp_ln103_fu_235_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten39_fu_106 <= add_ln103_1_fu_241_p2;
                end if;
            end if; 
        end if;
    end process;

    r_1_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_1_fu_94 <= ap_const_lv5_0;
                elsif (((icmp_ln103_fu_235_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    r_1_fu_94 <= select_ln104_1_fu_346_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln103_fu_235_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln113_1_reg_1030 <= add_ln113_1_fu_480_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln113_1_reg_1030_pp0_iter2_reg <= add_ln113_1_reg_1030;
                add_ln113_1_reg_1030_pp0_iter3_reg <= add_ln113_1_reg_1030_pp0_iter2_reg;
                add_ln113_1_reg_1030_pp0_iter4_reg <= add_ln113_1_reg_1030_pp0_iter3_reg;
                add_ln113_1_reg_1030_pp0_iter5_reg <= add_ln113_1_reg_1030_pp0_iter4_reg;
                add_ln113_1_reg_1030_pp0_iter6_reg <= add_ln113_1_reg_1030_pp0_iter5_reg;
                add_ln113_1_reg_1030_pp0_iter7_reg <= add_ln113_1_reg_1030_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                layer1_conv_load_1_reg_1062_pp0_iter3_reg <= layer1_conv_load_1_reg_1062;
                layer1_conv_load_2_reg_1069_pp0_iter3_reg <= layer1_conv_load_2_reg_1069;
                layer1_conv_load_2_reg_1069_pp0_iter4_reg <= layer1_conv_load_2_reg_1069_pp0_iter3_reg;
                layer1_conv_load_2_reg_1069_pp0_iter5_reg <= layer1_conv_load_2_reg_1069_pp0_iter4_reg;
                layer1_conv_load_3_reg_1076_pp0_iter3_reg <= layer1_conv_load_3_reg_1076;
                layer1_conv_load_3_reg_1076_pp0_iter4_reg <= layer1_conv_load_3_reg_1076_pp0_iter3_reg;
                layer1_conv_load_3_reg_1076_pp0_iter5_reg <= layer1_conv_load_3_reg_1076_pp0_iter4_reg;
                layer1_conv_load_3_reg_1076_pp0_iter6_reg <= layer1_conv_load_3_reg_1076_pp0_iter5_reg;
                layer1_conv_load_3_reg_1076_pp0_iter7_reg <= layer1_conv_load_3_reg_1076_pp0_iter6_reg;
                select_ln110_1_reg_1090 <= select_ln110_1_fu_804_p3;
                select_ln110_1_reg_1090_pp0_iter5_reg <= select_ln110_1_reg_1090;
                select_ln110_2_reg_1097 <= select_ln110_2_fu_892_p3;
                select_ln110_2_reg_1097_pp0_iter7_reg <= select_ln110_2_reg_1097;
                select_ln110_reg_1083 <= select_ln110_fu_714_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                layer1_conv_load_1_reg_1062 <= layer1_conv_q2;
                layer1_conv_load_2_reg_1069 <= layer1_conv_q1;
                layer1_conv_load_3_reg_1076 <= layer1_conv_q0;
                layer1_conv_load_reg_1055 <= layer1_conv_q3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln103_1_fu_241_p2 <= std_logic_vector(unsigned(indvar_flatten39_fu_106) + unsigned(ap_const_lv12_1));
    add_ln103_fu_256_p2 <= std_logic_vector(unsigned(f_fu_102) + unsigned(ap_const_lv3_1));
    add_ln104_1_fu_634_p2 <= std_logic_vector(unsigned(indvar_flatten15_fu_98) + unsigned(ap_const_lv10_1));
    add_ln104_fu_326_p2 <= std_logic_vector(unsigned(select_ln103_fu_268_p3) + unsigned(ap_const_lv5_1));
    add_ln105_fu_628_p2 <= std_logic_vector(unsigned(select_ln104_fu_338_p3) + unsigned(ap_const_lv5_1));
    add_ln109_1_fu_527_p2 <= std_logic_vector(unsigned(sub_ln109_1_fu_456_p2) + unsigned(zext_ln109_4_fu_494_p1));
    add_ln109_2_fu_570_p2 <= std_logic_vector(unsigned(trunc_ln109_fu_562_p1) + unsigned(zext_ln109_7_fu_566_p1));
    add_ln109_3_fu_584_p2 <= std_logic_vector(unsigned(tmp_37_fu_576_p3) + unsigned(zext_ln103_fu_284_p1));
    add_ln109_4_fu_603_p2 <= std_logic_vector(unsigned(trunc_ln109_1_fu_595_p1) + unsigned(zext_ln109_9_fu_599_p1));
    add_ln109_5_fu_617_p2 <= std_logic_vector(unsigned(tmp_38_fu_609_p3) + unsigned(zext_ln103_fu_284_p1));
    add_ln109_fu_498_p2 <= std_logic_vector(unsigned(sub_ln109_fu_412_p2) + unsigned(zext_ln109_4_fu_494_p1));
    add_ln113_1_fu_480_p2 <= std_logic_vector(unsigned(tmp_33_fu_472_p3) + unsigned(zext_ln103_1_fu_288_p1));
    add_ln113_fu_466_p2 <= std_logic_vector(unsigned(sub_ln113_fu_366_p2) + unsigned(zext_ln113_1_fu_462_p1));
    and_ln103_fu_320_p2 <= (xor_ln103_fu_308_p2 and icmp_ln105_fu_314_p2);
    and_ln110_1_fu_792_p2 <= (or_ln110_2_fu_786_p2 and or_ln110_1_fu_768_p2);
    and_ln110_2_fu_798_p2 <= (grp_fu_869_p_dout0 and and_ln110_1_fu_792_p2);
    and_ln110_3_fu_880_p2 <= (or_ln110_4_fu_874_p2 and or_ln110_3_fu_856_p2);
    and_ln110_4_fu_886_p2 <= (grp_fu_873_p_dout0 and and_ln110_3_fu_880_p2);
    and_ln110_5_fu_972_p2 <= (or_ln110_6_fu_966_p2 and or_ln110_5_fu_948_p2);
    and_ln110_6_fu_978_p2 <= (grp_fu_877_p_dout0 and and_ln110_5_fu_972_p2);
    and_ln110_fu_708_p2 <= (or_ln110_fu_702_p2 and grp_fu_865_p_dout0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln103_fu_235_p2)
    begin
        if (((icmp_ln103_fu_235_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln110_1_fu_722_p1 <= layer1_conv_load_1_reg_1062_pp0_iter3_reg;
    bitcast_ln110_2_fu_739_p1 <= select_ln110_reg_1083;
    bitcast_ln110_3_fu_810_p1 <= layer1_conv_load_2_reg_1069_pp0_iter5_reg;
    bitcast_ln110_4_fu_827_p1 <= select_ln110_1_reg_1090_pp0_iter5_reg;
    bitcast_ln110_5_fu_902_p1 <= layer1_conv_load_3_reg_1076_pp0_iter7_reg;
    bitcast_ln110_6_fu_919_p1 <= select_ln110_2_reg_1097_pp0_iter7_reg;
    bitcast_ln110_fu_673_p1 <= layer1_conv_load_reg_1055;
    empty_fu_229_p2 <= (tmp_29_fu_221_p3 or ap_const_lv6_1);
    grp_fu_865_p_ce <= ap_const_logic_1;
    grp_fu_865_p_din0 <= layer1_conv_q3;
    grp_fu_865_p_din1 <= ap_const_lv32_CE6E6B28;
    grp_fu_865_p_opcode <= ap_const_lv5_2;
    grp_fu_869_p_ce <= ap_const_logic_1;
    grp_fu_869_p_din0 <= layer1_conv_load_1_reg_1062;
    grp_fu_869_p_din1 <= select_ln110_fu_714_p3;
    grp_fu_869_p_opcode <= ap_const_lv5_2;
    grp_fu_873_p_ce <= ap_const_logic_1;
    grp_fu_873_p_din0 <= layer1_conv_load_2_reg_1069_pp0_iter4_reg;
    grp_fu_873_p_din1 <= select_ln110_1_reg_1090;
    grp_fu_873_p_opcode <= ap_const_lv5_2;
    grp_fu_877_p_ce <= ap_const_logic_1;
    grp_fu_877_p_din0 <= layer1_conv_load_3_reg_1076_pp0_iter6_reg;
    grp_fu_877_p_din1 <= select_ln110_2_reg_1097;
    grp_fu_877_p_opcode <= ap_const_lv5_2;
    icmp_ln103_fu_235_p2 <= "1" when (indvar_flatten39_fu_106 = ap_const_lv12_F04) else "0";
    icmp_ln104_fu_262_p2 <= "1" when (indvar_flatten15_fu_98 = ap_const_lv10_3C1) else "0";
    icmp_ln105_fu_314_p2 <= "1" when (c_fu_90 = ap_const_lv5_1F) else "0";
    icmp_ln110_10_fu_936_p2 <= "0" when (tmp_10_fu_905_p4 = ap_const_lv8_FF) else "1";
    icmp_ln110_11_fu_942_p2 <= "1" when (trunc_ln110_5_fu_915_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_12_fu_954_p2 <= "0" when (tmp_11_fu_922_p4 = ap_const_lv8_FF) else "1";
    icmp_ln110_13_fu_960_p2 <= "1" when (trunc_ln110_6_fu_932_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_1_fu_696_p2 <= "1" when (trunc_ln110_fu_686_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_2_fu_756_p2 <= "0" when (tmp_5_fu_725_p4 = ap_const_lv8_FF) else "1";
    icmp_ln110_3_fu_762_p2 <= "1" when (trunc_ln110_1_fu_735_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_4_fu_774_p2 <= "0" when (tmp_6_fu_742_p4 = ap_const_lv8_FF) else "1";
    icmp_ln110_5_fu_780_p2 <= "1" when (trunc_ln110_2_fu_752_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_6_fu_844_p2 <= "0" when (tmp_8_fu_813_p4 = ap_const_lv8_FF) else "1";
    icmp_ln110_7_fu_850_p2 <= "1" when (trunc_ln110_3_fu_823_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_8_fu_862_p2 <= "0" when (tmp_9_fu_830_p4 = ap_const_lv8_FF) else "1";
    icmp_ln110_9_fu_868_p2 <= "1" when (trunc_ln110_4_fu_840_p1 = ap_const_lv23_0) else "0";
    icmp_ln110_fu_690_p2 <= "0" when (tmp_3_fu_676_p4 = ap_const_lv8_FF) else "1";
    layer1_conv_address0 <= zext_ln109_10_fu_623_p1(14 - 1 downto 0);
    layer1_conv_address1 <= zext_ln109_6_fu_551_p1(14 - 1 downto 0);
    layer1_conv_address2 <= zext_ln109_8_fu_590_p1(14 - 1 downto 0);
    layer1_conv_address3 <= zext_ln109_5_fu_522_p1(14 - 1 downto 0);

    layer1_conv_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer1_conv_ce0 <= ap_const_logic_1;
        else 
            layer1_conv_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    layer1_conv_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer1_conv_ce1 <= ap_const_logic_1;
        else 
            layer1_conv_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    layer1_conv_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer1_conv_ce2 <= ap_const_logic_1;
        else 
            layer1_conv_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    layer1_conv_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer1_conv_ce3 <= ap_const_logic_1;
        else 
            layer1_conv_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    layer1_pool_address0 <= zext_ln113_2_fu_898_p1(12 - 1 downto 0);

    layer1_pool_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            layer1_pool_ce0 <= ap_const_logic_1;
        else 
            layer1_pool_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer1_pool_d0 <= 
        layer1_conv_load_3_reg_1076_pp0_iter7_reg when (and_ln110_6_fu_978_p2(0) = '1') else 
        select_ln110_2_reg_1097_pp0_iter7_reg;

    layer1_pool_we0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            layer1_pool_we0 <= ap_const_logic_1;
        else 
            layer1_pool_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln104_fu_332_p2 <= (icmp_ln104_fu_262_p2 or and_ln103_fu_320_p2);
    or_ln109_fu_556_p2 <= (tmp_34_fu_486_p3 or ap_const_lv6_1);
    or_ln110_1_fu_768_p2 <= (icmp_ln110_3_fu_762_p2 or icmp_ln110_2_fu_756_p2);
    or_ln110_2_fu_786_p2 <= (icmp_ln110_5_fu_780_p2 or icmp_ln110_4_fu_774_p2);
    or_ln110_3_fu_856_p2 <= (icmp_ln110_7_fu_850_p2 or icmp_ln110_6_fu_844_p2);
    or_ln110_4_fu_874_p2 <= (icmp_ln110_9_fu_868_p2 or icmp_ln110_8_fu_862_p2);
    or_ln110_5_fu_948_p2 <= (icmp_ln110_11_fu_942_p2 or icmp_ln110_10_fu_936_p2);
    or_ln110_6_fu_966_p2 <= (icmp_ln110_13_fu_960_p2 or icmp_ln110_12_fu_954_p2);
    or_ln110_fu_702_p2 <= (icmp_ln110_fu_690_p2 or icmp_ln110_1_fu_696_p2);
    p_mid113_fu_418_p2 <= (p_mid_fu_372_p3 or ap_const_lv6_1);
    p_mid_fu_372_p3 <= (add_ln104_fu_326_p2 & ap_const_lv1_0);
    select_ln103_1_fu_276_p3 <= 
        add_ln103_fu_256_p2 when (icmp_ln104_fu_262_p2(0) = '1') else 
        f_fu_102;
    select_ln103_2_fu_292_p3 <= 
        ap_const_lv6_0 when (icmp_ln104_fu_262_p2(0) = '1') else 
        tmp_29_fu_221_p3;
    select_ln103_3_fu_300_p3 <= 
        ap_const_lv6_1 when (icmp_ln104_fu_262_p2(0) = '1') else 
        empty_fu_229_p2;
    select_ln103_fu_268_p3 <= 
        ap_const_lv5_0 when (icmp_ln104_fu_262_p2(0) = '1') else 
        r_1_fu_94;
    select_ln104_1_fu_346_p3 <= 
        add_ln104_fu_326_p2 when (and_ln103_fu_320_p2(0) = '1') else 
        select_ln103_fu_268_p3;
    select_ln104_2_fu_380_p3 <= 
        p_mid_fu_372_p3 when (and_ln103_fu_320_p2(0) = '1') else 
        select_ln103_2_fu_292_p3;
    select_ln104_3_fu_424_p3 <= 
        p_mid113_fu_418_p2 when (and_ln103_fu_320_p2(0) = '1') else 
        select_ln103_3_fu_300_p3;
    select_ln104_4_fu_640_p3 <= 
        ap_const_lv10_1 when (icmp_ln104_fu_262_p2(0) = '1') else 
        add_ln104_1_fu_634_p2;
    select_ln104_fu_338_p3 <= 
        ap_const_lv5_0 when (or_ln104_fu_332_p2(0) = '1') else 
        c_fu_90;
    select_ln110_1_fu_804_p3 <= 
        layer1_conv_load_1_reg_1062_pp0_iter3_reg when (and_ln110_2_fu_798_p2(0) = '1') else 
        select_ln110_reg_1083;
    select_ln110_2_fu_892_p3 <= 
        layer1_conv_load_2_reg_1069_pp0_iter5_reg when (and_ln110_4_fu_886_p2(0) = '1') else 
        select_ln110_1_reg_1090_pp0_iter5_reg;
    select_ln110_fu_714_p3 <= 
        layer1_conv_load_reg_1055 when (and_ln110_fu_708_p2(0) = '1') else 
        ap_const_lv32_CE6E6B28;
    sub_ln109_1_fu_456_p2 <= std_logic_vector(unsigned(zext_ln109_2_fu_440_p1) - unsigned(zext_ln109_3_fu_452_p1));
    sub_ln109_fu_412_p2 <= std_logic_vector(unsigned(zext_ln109_fu_396_p1) - unsigned(zext_ln109_1_fu_408_p1));
    sub_ln113_fu_366_p2 <= std_logic_vector(unsigned(tmp_fu_358_p3) - unsigned(zext_ln113_fu_354_p1));
    tmp_10_fu_905_p4 <= bitcast_ln110_5_fu_902_p1(30 downto 23);
    tmp_11_fu_922_p4 <= bitcast_ln110_6_fu_919_p1(30 downto 23);
    tmp_13_fu_388_p3 <= (select_ln104_2_fu_380_p3 & ap_const_lv6_0);
    tmp_14_fu_400_p3 <= (select_ln104_2_fu_380_p3 & ap_const_lv1_0);
    tmp_15_fu_432_p3 <= (select_ln104_3_fu_424_p3 & ap_const_lv6_0);
    tmp_16_fu_444_p3 <= (select_ln104_3_fu_424_p3 & ap_const_lv1_0);
    tmp_29_fu_221_p3 <= (r_1_fu_94 & ap_const_lv1_0);
    tmp_33_fu_472_p3 <= (add_ln113_fu_466_p2 & ap_const_lv2_0);
    tmp_34_fu_486_p3 <= (select_ln104_fu_338_p3 & ap_const_lv1_0);
    tmp_35_fu_514_p3 <= (tmp_40_cast_fu_504_p4 & select_ln103_1_fu_276_p3);
    tmp_36_fu_543_p3 <= (tmp_44_cast_fu_533_p4 & select_ln103_1_fu_276_p3);
    tmp_37_fu_576_p3 <= (add_ln109_2_fu_570_p2 & ap_const_lv2_0);
    tmp_38_fu_609_p3 <= (add_ln109_4_fu_603_p2 & ap_const_lv2_0);
    tmp_3_fu_676_p4 <= bitcast_ln110_fu_673_p1(30 downto 23);
    tmp_40_cast_fu_504_p4 <= add_ln109_fu_498_p2(11 downto 1);
    tmp_44_cast_fu_533_p4 <= add_ln109_1_fu_527_p2(11 downto 1);
    tmp_5_fu_725_p4 <= bitcast_ln110_1_fu_722_p1(30 downto 23);
    tmp_6_fu_742_p4 <= bitcast_ln110_2_fu_739_p1(30 downto 23);
    tmp_8_fu_813_p4 <= bitcast_ln110_3_fu_810_p1(30 downto 23);
    tmp_9_fu_830_p4 <= bitcast_ln110_4_fu_827_p1(30 downto 23);
    tmp_fu_358_p3 <= (select_ln104_1_fu_346_p3 & ap_const_lv5_0);
    trunc_ln109_1_fu_595_p1 <= sub_ln109_1_fu_456_p2(12 - 1 downto 0);
    trunc_ln109_fu_562_p1 <= sub_ln109_fu_412_p2(12 - 1 downto 0);
    trunc_ln110_1_fu_735_p1 <= bitcast_ln110_1_fu_722_p1(23 - 1 downto 0);
    trunc_ln110_2_fu_752_p1 <= bitcast_ln110_2_fu_739_p1(23 - 1 downto 0);
    trunc_ln110_3_fu_823_p1 <= bitcast_ln110_3_fu_810_p1(23 - 1 downto 0);
    trunc_ln110_4_fu_840_p1 <= bitcast_ln110_4_fu_827_p1(23 - 1 downto 0);
    trunc_ln110_5_fu_915_p1 <= bitcast_ln110_5_fu_902_p1(23 - 1 downto 0);
    trunc_ln110_6_fu_932_p1 <= bitcast_ln110_6_fu_919_p1(23 - 1 downto 0);
    trunc_ln110_fu_686_p1 <= bitcast_ln110_fu_673_p1(23 - 1 downto 0);
    xor_ln103_fu_308_p2 <= (icmp_ln104_fu_262_p2 xor ap_const_lv1_1);
    zext_ln103_1_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln103_1_fu_276_p3),12));
    zext_ln103_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln103_1_fu_276_p3),14));
    zext_ln109_10_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln109_5_fu_617_p2),64));
    zext_ln109_1_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_400_p3),62));
    zext_ln109_2_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_432_p3),62));
    zext_ln109_3_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_444_p3),62));
    zext_ln109_4_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_fu_486_p3),62));
    zext_ln109_5_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_514_p3),64));
    zext_ln109_6_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_543_p3),64));
    zext_ln109_7_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln109_fu_556_p2),12));
    zext_ln109_8_fu_590_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln109_3_fu_584_p2),64));
    zext_ln109_9_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln109_fu_556_p2),12));
    zext_ln109_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_388_p3),62));
    zext_ln113_1_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln104_fu_338_p3),10));
    zext_ln113_2_fu_898_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln113_1_reg_1030_pp0_iter7_reg),64));
    zext_ln113_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln104_1_fu_346_p3),10));
end behav;
