-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_147_17_VITIS_LOOP_148_18_VITIS_LOOP_149_19 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer2_pool_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    layer2_pool_ce0 : OUT STD_LOGIC;
    layer2_pool_we0 : OUT STD_LOGIC;
    layer2_pool_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    layer2_conv_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    layer2_conv_ce0 : OUT STD_LOGIC;
    layer2_conv_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    layer2_conv_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    layer2_conv_ce1 : OUT STD_LOGIC;
    layer2_conv_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    layer2_conv_address2 : OUT STD_LOGIC_VECTOR (12 downto 0);
    layer2_conv_ce2 : OUT STD_LOGIC;
    layer2_conv_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    layer2_conv_address3 : OUT STD_LOGIC_VECTOR (12 downto 0);
    layer2_conv_ce3 : OUT STD_LOGIC;
    layer2_conv_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_865_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_865_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_865_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_865_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_865_p_ce : OUT STD_LOGIC;
    grp_fu_869_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_869_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_869_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_869_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_869_p_ce : OUT STD_LOGIC;
    grp_fu_873_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_873_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_873_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_873_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_873_p_ce : OUT STD_LOGIC;
    grp_fu_877_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_877_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_877_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_877_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_877_p_ce : OUT STD_LOGIC );
end;


architecture behav of cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_147_17_VITIS_LOOP_148_18_VITIS_LOOP_149_19 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_CE6E6B28 : STD_LOGIC_VECTOR (31 downto 0) := "11001110011011100110101100101000";
    constant ap_const_lv11_620 : STD_LOGIC_VECTOR (10 downto 0) := "11000100000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv10_1D : STD_LOGIC_VECTOR (9 downto 0) := "0000011101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln147_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln147_reg_956 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln148_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln148_reg_960 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln157_1_fu_454_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln157_1_reg_970_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal layer2_conv_load_reg_995 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_1_reg_1002 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_1_reg_1002_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_2_reg_1009 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_2_reg_1009_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_2_reg_1009_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_2_reg_1009_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_3_reg_1016 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_3_reg_1016_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_3_reg_1016_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_3_reg_1016_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_3_reg_1016_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal layer2_conv_load_3_reg_1016_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_fu_644_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_reg_1023 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_1_fu_734_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_1_reg_1030 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_1_reg_1030_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_2_fu_822_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_2_reg_1037 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln154_2_reg_1037_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln153_3_fu_492_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln153_4_fu_517_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln153_6_fu_552_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln153_7_fu_577_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln157_2_fu_828_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_78 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln149_fu_582_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_82 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln148_1_fu_352_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten124_fu_86 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln148_4_fu_233_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten124_load : STD_LOGIC_VECTOR (7 downto 0);
    signal f_fu_90 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln147_1_fu_287_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten148_fu_94 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln147_1_fu_212_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten148_load : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln148_1_fu_227_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_254_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln147_fu_274_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_262_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln149_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln147_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln147_fu_280_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln147_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln148_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln148_fu_333_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_368_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_360_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln157_fu_376_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_mid2_fu_386_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln147_2_fu_302_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln148_2_fu_394_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln153_fu_406_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln153_fu_406_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_mid1122_fu_412_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln147_3_fu_309_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln148_3_fu_418_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln153_1_fu_430_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln153_1_fu_430_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln148_fu_344_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln157_fu_380_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln157_1_fu_436_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln157_fu_440_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_446_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln147_1_fu_298_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_fu_460_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln153_fu_406_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln153_2_fu_468_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln153_fu_472_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_fu_478_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln147_fu_294_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln153_1_fu_486_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln153_1_fu_430_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln153_2_fu_497_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_10_fu_503_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln153_3_fu_511_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln153_fu_522_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln153_5_fu_528_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln153_4_fu_532_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_13_fu_538_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln153_5_fu_546_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln153_6_fu_557_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_14_fu_563_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln153_7_fu_571_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal bitcast_ln154_fu_603_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_606_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_fu_616_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_1_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln154_1_fu_652_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln154_2_fu_669_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_655_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_1_fu_665_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_3_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_2_fu_686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_672_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_2_fu_682_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_5_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_4_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_1_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_2_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_1_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_2_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln154_3_fu_740_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln154_4_fu_757_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_743_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_3_fu_753_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_7_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_6_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_760_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_4_fu_770_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_9_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_8_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_3_fu_786_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_4_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_3_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_4_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln154_5_fu_832_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln154_6_fu_849_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_835_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_5_fu_845_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_11_fu_872_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_10_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_852_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln154_6_fu_862_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln154_13_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_12_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_5_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln154_6_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_5_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln154_6_fu_908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal mul_ln153_1_fu_430_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln153_fu_406_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cnn_predict_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cnn_predict_mul_5ns_6ns_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component cnn_predict_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_5ns_6ns_10_1_1_U63 : component cnn_predict_mul_5ns_6ns_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 6,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln153_fu_406_p0,
        din1 => mul_ln153_fu_406_p1,
        dout => mul_ln153_fu_406_p2);

    mul_5ns_6ns_10_1_1_U64 : component cnn_predict_mul_5ns_6ns_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 6,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln153_1_fu_430_p0,
        din1 => mul_ln153_1_fu_430_p1,
        dout => mul_ln153_1_fu_430_p2);

    flow_control_loop_pipe_sequential_init_U : component cnn_predict_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    c_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_78 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln147_reg_956 = ap_const_lv1_0))) then 
                    c_fu_78 <= add_ln149_fu_582_p2;
                end if;
            end if; 
        end if;
    end process;

    f_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_90 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln147_reg_956 = ap_const_lv1_0))) then 
                    f_fu_90 <= select_ln147_1_fu_287_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten124_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln147_fu_206_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten124_fu_86 <= select_ln148_4_fu_233_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten124_fu_86 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten148_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln147_fu_206_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten148_fu_94 <= add_ln147_1_fu_212_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten148_fu_94 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_82 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln147_reg_956 = ap_const_lv1_0))) then 
                    r_fu_82 <= select_ln148_1_fu_352_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln147_reg_956 = ap_const_lv1_0))) then
                add_ln157_1_reg_970 <= add_ln157_1_fu_454_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln157_1_reg_970_pp0_iter2_reg <= add_ln157_1_reg_970;
                add_ln157_1_reg_970_pp0_iter3_reg <= add_ln157_1_reg_970_pp0_iter2_reg;
                add_ln157_1_reg_970_pp0_iter4_reg <= add_ln157_1_reg_970_pp0_iter3_reg;
                add_ln157_1_reg_970_pp0_iter5_reg <= add_ln157_1_reg_970_pp0_iter4_reg;
                add_ln157_1_reg_970_pp0_iter6_reg <= add_ln157_1_reg_970_pp0_iter5_reg;
                add_ln157_1_reg_970_pp0_iter7_reg <= add_ln157_1_reg_970_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                layer2_conv_load_1_reg_1002_pp0_iter3_reg <= layer2_conv_load_1_reg_1002;
                layer2_conv_load_2_reg_1009_pp0_iter3_reg <= layer2_conv_load_2_reg_1009;
                layer2_conv_load_2_reg_1009_pp0_iter4_reg <= layer2_conv_load_2_reg_1009_pp0_iter3_reg;
                layer2_conv_load_2_reg_1009_pp0_iter5_reg <= layer2_conv_load_2_reg_1009_pp0_iter4_reg;
                layer2_conv_load_3_reg_1016_pp0_iter3_reg <= layer2_conv_load_3_reg_1016;
                layer2_conv_load_3_reg_1016_pp0_iter4_reg <= layer2_conv_load_3_reg_1016_pp0_iter3_reg;
                layer2_conv_load_3_reg_1016_pp0_iter5_reg <= layer2_conv_load_3_reg_1016_pp0_iter4_reg;
                layer2_conv_load_3_reg_1016_pp0_iter6_reg <= layer2_conv_load_3_reg_1016_pp0_iter5_reg;
                layer2_conv_load_3_reg_1016_pp0_iter7_reg <= layer2_conv_load_3_reg_1016_pp0_iter6_reg;
                select_ln154_1_reg_1030 <= select_ln154_1_fu_734_p3;
                select_ln154_1_reg_1030_pp0_iter5_reg <= select_ln154_1_reg_1030;
                select_ln154_2_reg_1037 <= select_ln154_2_fu_822_p3;
                select_ln154_2_reg_1037_pp0_iter7_reg <= select_ln154_2_reg_1037;
                select_ln154_reg_1023 <= select_ln154_fu_644_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln147_reg_956 <= icmp_ln147_fu_206_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln147_fu_206_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln148_reg_960 <= icmp_ln148_fu_221_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                layer2_conv_load_1_reg_1002 <= layer2_conv_q2;
                layer2_conv_load_2_reg_1009 <= layer2_conv_q1;
                layer2_conv_load_3_reg_1016 <= layer2_conv_q0;
                layer2_conv_load_reg_995 <= layer2_conv_q3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln147_1_fu_212_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten148_load) + unsigned(ap_const_lv11_1));
    add_ln147_fu_274_p2 <= std_logic_vector(unsigned(f_fu_90) + unsigned(ap_const_lv4_1));
    add_ln148_1_fu_227_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten124_load) + unsigned(ap_const_lv8_1));
    add_ln148_fu_333_p2 <= std_logic_vector(unsigned(select_ln147_fu_280_p3) + unsigned(ap_const_lv4_1));
    add_ln149_fu_582_p2 <= std_logic_vector(unsigned(select_ln148_fu_344_p3) + unsigned(ap_const_lv4_1));
    add_ln153_1_fu_486_p2 <= std_logic_vector(unsigned(tmp_9_fu_478_p3) + unsigned(zext_ln147_fu_294_p1));
    add_ln153_2_fu_497_p2 <= std_logic_vector(unsigned(mul_ln153_1_fu_430_p2) + unsigned(zext_ln153_2_fu_468_p1));
    add_ln153_3_fu_511_p2 <= std_logic_vector(unsigned(tmp_10_fu_503_p3) + unsigned(zext_ln147_fu_294_p1));
    add_ln153_4_fu_532_p2 <= std_logic_vector(unsigned(mul_ln153_fu_406_p2) + unsigned(zext_ln153_5_fu_528_p1));
    add_ln153_5_fu_546_p2 <= std_logic_vector(unsigned(tmp_13_fu_538_p3) + unsigned(zext_ln147_fu_294_p1));
    add_ln153_6_fu_557_p2 <= std_logic_vector(unsigned(mul_ln153_1_fu_430_p2) + unsigned(zext_ln153_5_fu_528_p1));
    add_ln153_7_fu_571_p2 <= std_logic_vector(unsigned(tmp_14_fu_563_p3) + unsigned(zext_ln147_fu_294_p1));
    add_ln153_fu_472_p2 <= std_logic_vector(unsigned(mul_ln153_fu_406_p2) + unsigned(zext_ln153_2_fu_468_p1));
    add_ln157_1_fu_454_p2 <= std_logic_vector(unsigned(tmp_7_fu_446_p3) + unsigned(zext_ln147_1_fu_298_p1));
    add_ln157_fu_440_p2 <= std_logic_vector(unsigned(sub_ln157_fu_380_p2) + unsigned(zext_ln157_1_fu_436_p1));
    and_ln147_fu_327_p2 <= (xor_ln147_fu_316_p2 and icmp_ln149_fu_321_p2);
    and_ln154_1_fu_722_p2 <= (or_ln154_2_fu_716_p2 and or_ln154_1_fu_698_p2);
    and_ln154_2_fu_728_p2 <= (grp_fu_869_p_dout0 and and_ln154_1_fu_722_p2);
    and_ln154_3_fu_810_p2 <= (or_ln154_4_fu_804_p2 and or_ln154_3_fu_786_p2);
    and_ln154_4_fu_816_p2 <= (grp_fu_873_p_dout0 and and_ln154_3_fu_810_p2);
    and_ln154_5_fu_902_p2 <= (or_ln154_6_fu_896_p2 and or_ln154_5_fu_878_p2);
    and_ln154_6_fu_908_p2 <= (grp_fu_877_p_dout0 and and_ln154_5_fu_902_p2);
    and_ln154_fu_638_p2 <= (or_ln154_fu_632_p2 and grp_fu_865_p_dout0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln147_fu_206_p2)
    begin
        if (((icmp_ln147_fu_206_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln147_reg_956)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln147_reg_956 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten124_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten124_fu_86)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten124_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten124_load <= indvar_flatten124_fu_86;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten148_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten148_fu_94)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten148_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten148_load <= indvar_flatten148_fu_94;
        end if; 
    end process;

    bitcast_ln154_1_fu_652_p1 <= layer2_conv_load_1_reg_1002_pp0_iter3_reg;
    bitcast_ln154_2_fu_669_p1 <= select_ln154_reg_1023;
    bitcast_ln154_3_fu_740_p1 <= layer2_conv_load_2_reg_1009_pp0_iter5_reg;
    bitcast_ln154_4_fu_757_p1 <= select_ln154_1_reg_1030_pp0_iter5_reg;
    bitcast_ln154_5_fu_832_p1 <= layer2_conv_load_3_reg_1016_pp0_iter7_reg;
    bitcast_ln154_6_fu_849_p1 <= select_ln154_2_reg_1037_pp0_iter7_reg;
    bitcast_ln154_fu_603_p1 <= layer2_conv_load_reg_995;
    empty_fu_262_p2 <= (tmp_s_fu_254_p3 or ap_const_lv5_1);
    grp_fu_865_p_ce <= ap_const_logic_1;
    grp_fu_865_p_din0 <= layer2_conv_q3;
    grp_fu_865_p_din1 <= ap_const_lv32_CE6E6B28;
    grp_fu_865_p_opcode <= ap_const_lv5_2;
    grp_fu_869_p_ce <= ap_const_logic_1;
    grp_fu_869_p_din0 <= layer2_conv_load_1_reg_1002;
    grp_fu_869_p_din1 <= select_ln154_fu_644_p3;
    grp_fu_869_p_opcode <= ap_const_lv5_2;
    grp_fu_873_p_ce <= ap_const_logic_1;
    grp_fu_873_p_din0 <= layer2_conv_load_2_reg_1009_pp0_iter4_reg;
    grp_fu_873_p_din1 <= select_ln154_1_reg_1030;
    grp_fu_873_p_opcode <= ap_const_lv5_2;
    grp_fu_877_p_ce <= ap_const_logic_1;
    grp_fu_877_p_din0 <= layer2_conv_load_3_reg_1016_pp0_iter6_reg;
    grp_fu_877_p_din1 <= select_ln154_2_reg_1037;
    grp_fu_877_p_opcode <= ap_const_lv5_2;
    icmp_ln147_fu_206_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten148_load = ap_const_lv11_620) else "0";
    icmp_ln148_fu_221_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten124_load = ap_const_lv8_C4) else "0";
    icmp_ln149_fu_321_p2 <= "1" when (c_fu_78 = ap_const_lv4_E) else "0";
    icmp_ln154_10_fu_866_p2 <= "0" when (tmp_21_fu_835_p4 = ap_const_lv8_FF) else "1";
    icmp_ln154_11_fu_872_p2 <= "1" when (trunc_ln154_5_fu_845_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_12_fu_884_p2 <= "0" when (tmp_22_fu_852_p4 = ap_const_lv8_FF) else "1";
    icmp_ln154_13_fu_890_p2 <= "1" when (trunc_ln154_6_fu_862_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_1_fu_626_p2 <= "1" when (trunc_ln154_fu_616_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_2_fu_686_p2 <= "0" when (tmp_15_fu_655_p4 = ap_const_lv8_FF) else "1";
    icmp_ln154_3_fu_692_p2 <= "1" when (trunc_ln154_1_fu_665_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_4_fu_704_p2 <= "0" when (tmp_16_fu_672_p4 = ap_const_lv8_FF) else "1";
    icmp_ln154_5_fu_710_p2 <= "1" when (trunc_ln154_2_fu_682_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_6_fu_774_p2 <= "0" when (tmp_18_fu_743_p4 = ap_const_lv8_FF) else "1";
    icmp_ln154_7_fu_780_p2 <= "1" when (trunc_ln154_3_fu_753_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_8_fu_792_p2 <= "0" when (tmp_19_fu_760_p4 = ap_const_lv8_FF) else "1";
    icmp_ln154_9_fu_798_p2 <= "1" when (trunc_ln154_4_fu_770_p1 = ap_const_lv23_0) else "0";
    icmp_ln154_fu_620_p2 <= "0" when (tmp_11_fu_606_p4 = ap_const_lv8_FF) else "1";
    layer2_conv_address0 <= zext_ln153_7_fu_577_p1(13 - 1 downto 0);
    layer2_conv_address1 <= zext_ln153_4_fu_517_p1(13 - 1 downto 0);
    layer2_conv_address2 <= zext_ln153_6_fu_552_p1(13 - 1 downto 0);
    layer2_conv_address3 <= zext_ln153_3_fu_492_p1(13 - 1 downto 0);

    layer2_conv_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_conv_ce0 <= ap_const_logic_1;
        else 
            layer2_conv_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    layer2_conv_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_conv_ce1 <= ap_const_logic_1;
        else 
            layer2_conv_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    layer2_conv_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_conv_ce2 <= ap_const_logic_1;
        else 
            layer2_conv_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    layer2_conv_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer2_conv_ce3 <= ap_const_logic_1;
        else 
            layer2_conv_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    layer2_pool_address0 <= zext_ln157_2_fu_828_p1(11 - 1 downto 0);

    layer2_pool_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            layer2_pool_ce0 <= ap_const_logic_1;
        else 
            layer2_pool_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer2_pool_d0 <= 
        layer2_conv_load_3_reg_1016_pp0_iter7_reg when (and_ln154_6_fu_908_p2(0) = '1') else 
        select_ln154_2_reg_1037_pp0_iter7_reg;

    layer2_pool_we0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            layer2_pool_we0 <= ap_const_logic_1;
        else 
            layer2_pool_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln153_1_fu_430_p0 <= mul_ln153_1_fu_430_p00(5 - 1 downto 0);
    mul_ln153_1_fu_430_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln148_3_fu_418_p3),10));
    mul_ln153_1_fu_430_p1 <= ap_const_lv10_1D(6 - 1 downto 0);
    mul_ln153_fu_406_p0 <= mul_ln153_fu_406_p00(5 - 1 downto 0);
    mul_ln153_fu_406_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln148_2_fu_394_p3),10));
    mul_ln153_fu_406_p1 <= ap_const_lv10_1D(6 - 1 downto 0);
    or_ln148_fu_339_p2 <= (icmp_ln148_reg_960 or and_ln147_fu_327_p2);
    or_ln153_fu_522_p2 <= (tmp_8_fu_460_p3 or ap_const_lv5_1);
    or_ln154_1_fu_698_p2 <= (icmp_ln154_3_fu_692_p2 or icmp_ln154_2_fu_686_p2);
    or_ln154_2_fu_716_p2 <= (icmp_ln154_5_fu_710_p2 or icmp_ln154_4_fu_704_p2);
    or_ln154_3_fu_786_p2 <= (icmp_ln154_7_fu_780_p2 or icmp_ln154_6_fu_774_p2);
    or_ln154_4_fu_804_p2 <= (icmp_ln154_9_fu_798_p2 or icmp_ln154_8_fu_792_p2);
    or_ln154_5_fu_878_p2 <= (icmp_ln154_11_fu_872_p2 or icmp_ln154_10_fu_866_p2);
    or_ln154_6_fu_896_p2 <= (icmp_ln154_13_fu_890_p2 or icmp_ln154_12_fu_884_p2);
    or_ln154_fu_632_p2 <= (icmp_ln154_fu_620_p2 or icmp_ln154_1_fu_626_p2);
    p_mid1122_fu_412_p2 <= (p_mid2_fu_386_p3 or ap_const_lv5_1);
    p_mid2_fu_386_p3 <= (add_ln148_fu_333_p2 & ap_const_lv1_0);
    select_ln147_1_fu_287_p3 <= 
        add_ln147_fu_274_p2 when (icmp_ln148_reg_960(0) = '1') else 
        f_fu_90;
    select_ln147_2_fu_302_p3 <= 
        ap_const_lv5_0 when (icmp_ln148_reg_960(0) = '1') else 
        tmp_s_fu_254_p3;
    select_ln147_3_fu_309_p3 <= 
        ap_const_lv5_1 when (icmp_ln148_reg_960(0) = '1') else 
        empty_fu_262_p2;
    select_ln147_fu_280_p3 <= 
        ap_const_lv4_0 when (icmp_ln148_reg_960(0) = '1') else 
        r_fu_82;
    select_ln148_1_fu_352_p3 <= 
        add_ln148_fu_333_p2 when (and_ln147_fu_327_p2(0) = '1') else 
        select_ln147_fu_280_p3;
    select_ln148_2_fu_394_p3 <= 
        p_mid2_fu_386_p3 when (and_ln147_fu_327_p2(0) = '1') else 
        select_ln147_2_fu_302_p3;
    select_ln148_3_fu_418_p3 <= 
        p_mid1122_fu_412_p2 when (and_ln147_fu_327_p2(0) = '1') else 
        select_ln147_3_fu_309_p3;
    select_ln148_4_fu_233_p3 <= 
        ap_const_lv8_1 when (icmp_ln148_fu_221_p2(0) = '1') else 
        add_ln148_1_fu_227_p2;
    select_ln148_fu_344_p3 <= 
        ap_const_lv4_0 when (or_ln148_fu_339_p2(0) = '1') else 
        c_fu_78;
    select_ln154_1_fu_734_p3 <= 
        layer2_conv_load_1_reg_1002_pp0_iter3_reg when (and_ln154_2_fu_728_p2(0) = '1') else 
        select_ln154_reg_1023;
    select_ln154_2_fu_822_p3 <= 
        layer2_conv_load_2_reg_1009_pp0_iter5_reg when (and_ln154_4_fu_816_p2(0) = '1') else 
        select_ln154_1_reg_1030_pp0_iter5_reg;
    select_ln154_fu_644_p3 <= 
        layer2_conv_load_reg_995 when (and_ln154_fu_638_p2(0) = '1') else 
        ap_const_lv32_CE6E6B28;
    sub_ln157_fu_380_p2 <= std_logic_vector(unsigned(tmp_fu_360_p3) - unsigned(zext_ln157_fu_376_p1));
    tmp_10_fu_503_p3 <= (add_ln153_2_fu_497_p2 & ap_const_lv3_0);
    tmp_11_fu_606_p4 <= bitcast_ln154_fu_603_p1(30 downto 23);
    tmp_13_fu_538_p3 <= (add_ln153_4_fu_532_p2 & ap_const_lv3_0);
    tmp_14_fu_563_p3 <= (add_ln153_6_fu_557_p2 & ap_const_lv3_0);
    tmp_15_fu_655_p4 <= bitcast_ln154_1_fu_652_p1(30 downto 23);
    tmp_16_fu_672_p4 <= bitcast_ln154_2_fu_669_p1(30 downto 23);
    tmp_18_fu_743_p4 <= bitcast_ln154_3_fu_740_p1(30 downto 23);
    tmp_19_fu_760_p4 <= bitcast_ln154_4_fu_757_p1(30 downto 23);
    tmp_1_fu_368_p3 <= (select_ln148_1_fu_352_p3 & ap_const_lv1_0);
    tmp_21_fu_835_p4 <= bitcast_ln154_5_fu_832_p1(30 downto 23);
    tmp_22_fu_852_p4 <= bitcast_ln154_6_fu_849_p1(30 downto 23);
    tmp_7_fu_446_p3 <= (add_ln157_fu_440_p2 & ap_const_lv3_0);
    tmp_8_fu_460_p3 <= (select_ln148_fu_344_p3 & ap_const_lv1_0);
    tmp_9_fu_478_p3 <= (add_ln153_fu_472_p2 & ap_const_lv3_0);
    tmp_fu_360_p3 <= (select_ln148_1_fu_352_p3 & ap_const_lv4_0);
    tmp_s_fu_254_p3 <= (r_fu_82 & ap_const_lv1_0);
    trunc_ln154_1_fu_665_p1 <= bitcast_ln154_1_fu_652_p1(23 - 1 downto 0);
    trunc_ln154_2_fu_682_p1 <= bitcast_ln154_2_fu_669_p1(23 - 1 downto 0);
    trunc_ln154_3_fu_753_p1 <= bitcast_ln154_3_fu_740_p1(23 - 1 downto 0);
    trunc_ln154_4_fu_770_p1 <= bitcast_ln154_4_fu_757_p1(23 - 1 downto 0);
    trunc_ln154_5_fu_845_p1 <= bitcast_ln154_5_fu_832_p1(23 - 1 downto 0);
    trunc_ln154_6_fu_862_p1 <= bitcast_ln154_6_fu_849_p1(23 - 1 downto 0);
    trunc_ln154_fu_616_p1 <= bitcast_ln154_fu_603_p1(23 - 1 downto 0);
    xor_ln147_fu_316_p2 <= (icmp_ln148_reg_960 xor ap_const_lv1_1);
    zext_ln147_1_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln147_1_fu_287_p3),11));
    zext_ln147_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln147_1_fu_287_p3),13));
    zext_ln153_2_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_460_p3),10));
    zext_ln153_3_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_1_fu_486_p2),64));
    zext_ln153_4_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_3_fu_511_p2),64));
    zext_ln153_5_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln153_fu_522_p2),10));
    zext_ln153_6_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_5_fu_546_p2),64));
    zext_ln153_7_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_7_fu_571_p2),64));
    zext_ln157_1_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln148_fu_344_p3),8));
    zext_ln157_2_fu_828_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln157_1_reg_970_pp0_iter7_reg),64));
    zext_ln157_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_368_p3),8));
end behav;
