
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcnn_predict.h"

/*
* The configuration table for devices
*/

XCnn_predict_Config XCnn_predict_ConfigTable[XPAR_XCNN_PREDICT_NUM_INSTANCES] =
{
	{
		XPAR_CNN_PREDICT_0_DEVICE_ID,
		XPAR_CNN_PREDICT_0_S_AXI_CONTROL_BASEADDR
	}
};


