// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_147_17_VITIS_LOOP_148_18_VITIS_LOOP_149_19 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_pool_address0,
        layer2_pool_ce0,
        layer2_pool_we0,
        layer2_pool_d0,
        layer2_conv_address0,
        layer2_conv_ce0,
        layer2_conv_q0,
        layer2_conv_address1,
        layer2_conv_ce1,
        layer2_conv_q1,
        layer2_conv_address2,
        layer2_conv_ce2,
        layer2_conv_q2,
        layer2_conv_address3,
        layer2_conv_ce3,
        layer2_conv_q3,
        grp_fu_865_p_din0,
        grp_fu_865_p_din1,
        grp_fu_865_p_opcode,
        grp_fu_865_p_dout0,
        grp_fu_865_p_ce,
        grp_fu_869_p_din0,
        grp_fu_869_p_din1,
        grp_fu_869_p_opcode,
        grp_fu_869_p_dout0,
        grp_fu_869_p_ce,
        grp_fu_873_p_din0,
        grp_fu_873_p_din1,
        grp_fu_873_p_opcode,
        grp_fu_873_p_dout0,
        grp_fu_873_p_ce,
        grp_fu_877_p_din0,
        grp_fu_877_p_din1,
        grp_fu_877_p_opcode,
        grp_fu_877_p_dout0,
        grp_fu_877_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] layer2_pool_address0;
output   layer2_pool_ce0;
output   layer2_pool_we0;
output  [31:0] layer2_pool_d0;
output  [12:0] layer2_conv_address0;
output   layer2_conv_ce0;
input  [31:0] layer2_conv_q0;
output  [12:0] layer2_conv_address1;
output   layer2_conv_ce1;
input  [31:0] layer2_conv_q1;
output  [12:0] layer2_conv_address2;
output   layer2_conv_ce2;
input  [31:0] layer2_conv_q2;
output  [12:0] layer2_conv_address3;
output   layer2_conv_ce3;
input  [31:0] layer2_conv_q3;
output  [31:0] grp_fu_865_p_din0;
output  [31:0] grp_fu_865_p_din1;
output  [4:0] grp_fu_865_p_opcode;
input  [0:0] grp_fu_865_p_dout0;
output   grp_fu_865_p_ce;
output  [31:0] grp_fu_869_p_din0;
output  [31:0] grp_fu_869_p_din1;
output  [4:0] grp_fu_869_p_opcode;
input  [0:0] grp_fu_869_p_dout0;
output   grp_fu_869_p_ce;
output  [31:0] grp_fu_873_p_din0;
output  [31:0] grp_fu_873_p_din1;
output  [4:0] grp_fu_873_p_opcode;
input  [0:0] grp_fu_873_p_dout0;
output   grp_fu_873_p_ce;
output  [31:0] grp_fu_877_p_din0;
output  [31:0] grp_fu_877_p_din1;
output  [4:0] grp_fu_877_p_opcode;
input  [0:0] grp_fu_877_p_dout0;
output   grp_fu_877_p_ce;

reg ap_idle;
reg layer2_pool_ce0;
reg layer2_pool_we0;
reg layer2_conv_ce0;
reg layer2_conv_ce1;
reg layer2_conv_ce2;
reg layer2_conv_ce3;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln147_fu_206_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln147_reg_956;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln148_fu_221_p2;
reg   [0:0] icmp_ln148_reg_960;
wire   [10:0] add_ln157_1_fu_454_p2;
reg   [10:0] add_ln157_1_reg_970;
reg   [10:0] add_ln157_1_reg_970_pp0_iter2_reg;
reg   [10:0] add_ln157_1_reg_970_pp0_iter3_reg;
reg   [10:0] add_ln157_1_reg_970_pp0_iter4_reg;
reg   [10:0] add_ln157_1_reg_970_pp0_iter5_reg;
reg   [10:0] add_ln157_1_reg_970_pp0_iter6_reg;
reg   [10:0] add_ln157_1_reg_970_pp0_iter7_reg;
reg   [31:0] layer2_conv_load_reg_995;
reg   [31:0] layer2_conv_load_1_reg_1002;
reg   [31:0] layer2_conv_load_1_reg_1002_pp0_iter3_reg;
reg   [31:0] layer2_conv_load_2_reg_1009;
reg   [31:0] layer2_conv_load_2_reg_1009_pp0_iter3_reg;
reg   [31:0] layer2_conv_load_2_reg_1009_pp0_iter4_reg;
reg   [31:0] layer2_conv_load_2_reg_1009_pp0_iter5_reg;
reg   [31:0] layer2_conv_load_3_reg_1016;
reg   [31:0] layer2_conv_load_3_reg_1016_pp0_iter3_reg;
reg   [31:0] layer2_conv_load_3_reg_1016_pp0_iter4_reg;
reg   [31:0] layer2_conv_load_3_reg_1016_pp0_iter5_reg;
reg   [31:0] layer2_conv_load_3_reg_1016_pp0_iter6_reg;
reg   [31:0] layer2_conv_load_3_reg_1016_pp0_iter7_reg;
wire   [31:0] select_ln154_fu_644_p3;
reg   [31:0] select_ln154_reg_1023;
wire   [31:0] select_ln154_1_fu_734_p3;
reg   [31:0] select_ln154_1_reg_1030;
reg   [31:0] select_ln154_1_reg_1030_pp0_iter5_reg;
wire   [31:0] select_ln154_2_fu_822_p3;
reg   [31:0] select_ln154_2_reg_1037;
reg   [31:0] select_ln154_2_reg_1037_pp0_iter7_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln153_3_fu_492_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln153_4_fu_517_p1;
wire   [63:0] zext_ln153_6_fu_552_p1;
wire   [63:0] zext_ln153_7_fu_577_p1;
wire   [63:0] zext_ln157_2_fu_828_p1;
reg   [3:0] c_fu_78;
wire   [3:0] add_ln149_fu_582_p2;
wire    ap_loop_init;
reg   [3:0] r_fu_82;
wire   [3:0] select_ln148_1_fu_352_p3;
reg   [7:0] indvar_flatten124_fu_86;
wire   [7:0] select_ln148_4_fu_233_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten124_load;
reg   [3:0] f_fu_90;
wire   [3:0] select_ln147_1_fu_287_p3;
reg   [10:0] indvar_flatten148_fu_94;
wire   [10:0] add_ln147_1_fu_212_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten148_load;
wire   [7:0] add_ln148_1_fu_227_p2;
wire   [4:0] tmp_s_fu_254_p3;
wire   [3:0] add_ln147_fu_274_p2;
wire   [4:0] empty_fu_262_p2;
wire   [0:0] icmp_ln149_fu_321_p2;
wire   [0:0] xor_ln147_fu_316_p2;
wire   [3:0] select_ln147_fu_280_p3;
wire   [0:0] and_ln147_fu_327_p2;
wire   [0:0] or_ln148_fu_339_p2;
wire   [3:0] add_ln148_fu_333_p2;
wire   [4:0] tmp_1_fu_368_p3;
wire   [7:0] tmp_fu_360_p3;
wire   [7:0] zext_ln157_fu_376_p1;
wire   [4:0] p_mid2_fu_386_p3;
wire   [4:0] select_ln147_2_fu_302_p3;
wire   [4:0] select_ln148_2_fu_394_p3;
wire   [4:0] mul_ln153_fu_406_p0;
wire   [5:0] mul_ln153_fu_406_p1;
wire   [4:0] p_mid1122_fu_412_p2;
wire   [4:0] select_ln147_3_fu_309_p3;
wire   [4:0] select_ln148_3_fu_418_p3;
wire   [4:0] mul_ln153_1_fu_430_p0;
wire   [5:0] mul_ln153_1_fu_430_p1;
wire   [3:0] select_ln148_fu_344_p3;
wire   [7:0] sub_ln157_fu_380_p2;
wire   [7:0] zext_ln157_1_fu_436_p1;
wire   [7:0] add_ln157_fu_440_p2;
wire   [10:0] tmp_7_fu_446_p3;
wire   [10:0] zext_ln147_1_fu_298_p1;
wire   [4:0] tmp_8_fu_460_p3;
wire   [9:0] mul_ln153_fu_406_p2;
wire   [9:0] zext_ln153_2_fu_468_p1;
wire   [9:0] add_ln153_fu_472_p2;
wire   [12:0] tmp_9_fu_478_p3;
wire   [12:0] zext_ln147_fu_294_p1;
wire   [12:0] add_ln153_1_fu_486_p2;
wire   [9:0] mul_ln153_1_fu_430_p2;
wire   [9:0] add_ln153_2_fu_497_p2;
wire   [12:0] tmp_10_fu_503_p3;
wire   [12:0] add_ln153_3_fu_511_p2;
wire   [4:0] or_ln153_fu_522_p2;
wire   [9:0] zext_ln153_5_fu_528_p1;
wire   [9:0] add_ln153_4_fu_532_p2;
wire   [12:0] tmp_13_fu_538_p3;
wire   [12:0] add_ln153_5_fu_546_p2;
wire   [9:0] add_ln153_6_fu_557_p2;
wire   [12:0] tmp_14_fu_563_p3;
wire   [12:0] add_ln153_7_fu_571_p2;
wire   [31:0] bitcast_ln154_fu_603_p1;
wire   [7:0] tmp_11_fu_606_p4;
wire   [22:0] trunc_ln154_fu_616_p1;
wire   [0:0] icmp_ln154_1_fu_626_p2;
wire   [0:0] icmp_ln154_fu_620_p2;
wire   [0:0] or_ln154_fu_632_p2;
wire   [0:0] and_ln154_fu_638_p2;
wire   [31:0] bitcast_ln154_1_fu_652_p1;
wire   [31:0] bitcast_ln154_2_fu_669_p1;
wire   [7:0] tmp_15_fu_655_p4;
wire   [22:0] trunc_ln154_1_fu_665_p1;
wire   [0:0] icmp_ln154_3_fu_692_p2;
wire   [0:0] icmp_ln154_2_fu_686_p2;
wire   [7:0] tmp_16_fu_672_p4;
wire   [22:0] trunc_ln154_2_fu_682_p1;
wire   [0:0] icmp_ln154_5_fu_710_p2;
wire   [0:0] icmp_ln154_4_fu_704_p2;
wire   [0:0] or_ln154_1_fu_698_p2;
wire   [0:0] or_ln154_2_fu_716_p2;
wire   [0:0] and_ln154_1_fu_722_p2;
wire   [0:0] and_ln154_2_fu_728_p2;
wire   [31:0] bitcast_ln154_3_fu_740_p1;
wire   [31:0] bitcast_ln154_4_fu_757_p1;
wire   [7:0] tmp_18_fu_743_p4;
wire   [22:0] trunc_ln154_3_fu_753_p1;
wire   [0:0] icmp_ln154_7_fu_780_p2;
wire   [0:0] icmp_ln154_6_fu_774_p2;
wire   [7:0] tmp_19_fu_760_p4;
wire   [22:0] trunc_ln154_4_fu_770_p1;
wire   [0:0] icmp_ln154_9_fu_798_p2;
wire   [0:0] icmp_ln154_8_fu_792_p2;
wire   [0:0] or_ln154_3_fu_786_p2;
wire   [0:0] or_ln154_4_fu_804_p2;
wire   [0:0] and_ln154_3_fu_810_p2;
wire   [0:0] and_ln154_4_fu_816_p2;
wire   [31:0] bitcast_ln154_5_fu_832_p1;
wire   [31:0] bitcast_ln154_6_fu_849_p1;
wire   [7:0] tmp_21_fu_835_p4;
wire   [22:0] trunc_ln154_5_fu_845_p1;
wire   [0:0] icmp_ln154_11_fu_872_p2;
wire   [0:0] icmp_ln154_10_fu_866_p2;
wire   [7:0] tmp_22_fu_852_p4;
wire   [22:0] trunc_ln154_6_fu_862_p1;
wire   [0:0] icmp_ln154_13_fu_890_p2;
wire   [0:0] icmp_ln154_12_fu_884_p2;
wire   [0:0] or_ln154_5_fu_878_p2;
wire   [0:0] or_ln154_6_fu_896_p2;
wire   [0:0] and_ln154_5_fu_902_p2;
wire   [0:0] and_ln154_6_fu_908_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [9:0] mul_ln153_1_fu_430_p00;
wire   [9:0] mul_ln153_fu_406_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_predict_mul_5ns_6ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 10 ))
mul_5ns_6ns_10_1_1_U63(
    .din0(mul_ln153_fu_406_p0),
    .din1(mul_ln153_fu_406_p1),
    .dout(mul_ln153_fu_406_p2)
);

cnn_predict_mul_5ns_6ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 10 ))
mul_5ns_6ns_10_1_1_U64(
    .din0(mul_ln153_1_fu_430_p0),
    .din1(mul_ln153_1_fu_430_p1),
    .dout(mul_ln153_1_fu_430_p2)
);

cnn_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_78 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln147_reg_956 == 1'd0))) begin
            c_fu_78 <= add_ln149_fu_582_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            f_fu_90 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln147_reg_956 == 1'd0))) begin
            f_fu_90 <= select_ln147_1_fu_287_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln147_fu_206_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten124_fu_86 <= select_ln148_4_fu_233_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten124_fu_86 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln147_fu_206_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten148_fu_94 <= add_ln147_1_fu_212_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten148_fu_94 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_82 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln147_reg_956 == 1'd0))) begin
            r_fu_82 <= select_ln148_1_fu_352_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln147_reg_956 == 1'd0))) begin
        add_ln157_1_reg_970 <= add_ln157_1_fu_454_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln157_1_reg_970_pp0_iter2_reg <= add_ln157_1_reg_970;
        add_ln157_1_reg_970_pp0_iter3_reg <= add_ln157_1_reg_970_pp0_iter2_reg;
        add_ln157_1_reg_970_pp0_iter4_reg <= add_ln157_1_reg_970_pp0_iter3_reg;
        add_ln157_1_reg_970_pp0_iter5_reg <= add_ln157_1_reg_970_pp0_iter4_reg;
        add_ln157_1_reg_970_pp0_iter6_reg <= add_ln157_1_reg_970_pp0_iter5_reg;
        add_ln157_1_reg_970_pp0_iter7_reg <= add_ln157_1_reg_970_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        layer2_conv_load_1_reg_1002_pp0_iter3_reg <= layer2_conv_load_1_reg_1002;
        layer2_conv_load_2_reg_1009_pp0_iter3_reg <= layer2_conv_load_2_reg_1009;
        layer2_conv_load_2_reg_1009_pp0_iter4_reg <= layer2_conv_load_2_reg_1009_pp0_iter3_reg;
        layer2_conv_load_2_reg_1009_pp0_iter5_reg <= layer2_conv_load_2_reg_1009_pp0_iter4_reg;
        layer2_conv_load_3_reg_1016_pp0_iter3_reg <= layer2_conv_load_3_reg_1016;
        layer2_conv_load_3_reg_1016_pp0_iter4_reg <= layer2_conv_load_3_reg_1016_pp0_iter3_reg;
        layer2_conv_load_3_reg_1016_pp0_iter5_reg <= layer2_conv_load_3_reg_1016_pp0_iter4_reg;
        layer2_conv_load_3_reg_1016_pp0_iter6_reg <= layer2_conv_load_3_reg_1016_pp0_iter5_reg;
        layer2_conv_load_3_reg_1016_pp0_iter7_reg <= layer2_conv_load_3_reg_1016_pp0_iter6_reg;
        select_ln154_1_reg_1030 <= select_ln154_1_fu_734_p3;
        select_ln154_1_reg_1030_pp0_iter5_reg <= select_ln154_1_reg_1030;
        select_ln154_2_reg_1037 <= select_ln154_2_fu_822_p3;
        select_ln154_2_reg_1037_pp0_iter7_reg <= select_ln154_2_reg_1037;
        select_ln154_reg_1023 <= select_ln154_fu_644_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln147_reg_956 <= icmp_ln147_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln147_fu_206_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln148_reg_960 <= icmp_ln148_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer2_conv_load_1_reg_1002 <= layer2_conv_q2;
        layer2_conv_load_2_reg_1009 <= layer2_conv_q1;
        layer2_conv_load_3_reg_1016 <= layer2_conv_q0;
        layer2_conv_load_reg_995 <= layer2_conv_q3;
    end
end

always @ (*) begin
    if (((icmp_ln147_fu_206_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln147_reg_956 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten124_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten124_load = indvar_flatten124_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten148_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten148_load = indvar_flatten148_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_conv_ce0 = 1'b1;
    end else begin
        layer2_conv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_conv_ce1 = 1'b1;
    end else begin
        layer2_conv_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_conv_ce2 = 1'b1;
    end else begin
        layer2_conv_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_conv_ce3 = 1'b1;
    end else begin
        layer2_conv_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer2_pool_ce0 = 1'b1;
    end else begin
        layer2_pool_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer2_pool_we0 = 1'b1;
    end else begin
        layer2_pool_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln147_1_fu_212_p2 = (ap_sig_allocacmp_indvar_flatten148_load + 11'd1);

assign add_ln147_fu_274_p2 = (f_fu_90 + 4'd1);

assign add_ln148_1_fu_227_p2 = (ap_sig_allocacmp_indvar_flatten124_load + 8'd1);

assign add_ln148_fu_333_p2 = (select_ln147_fu_280_p3 + 4'd1);

assign add_ln149_fu_582_p2 = (select_ln148_fu_344_p3 + 4'd1);

assign add_ln153_1_fu_486_p2 = (tmp_9_fu_478_p3 + zext_ln147_fu_294_p1);

assign add_ln153_2_fu_497_p2 = (mul_ln153_1_fu_430_p2 + zext_ln153_2_fu_468_p1);

assign add_ln153_3_fu_511_p2 = (tmp_10_fu_503_p3 + zext_ln147_fu_294_p1);

assign add_ln153_4_fu_532_p2 = (mul_ln153_fu_406_p2 + zext_ln153_5_fu_528_p1);

assign add_ln153_5_fu_546_p2 = (tmp_13_fu_538_p3 + zext_ln147_fu_294_p1);

assign add_ln153_6_fu_557_p2 = (mul_ln153_1_fu_430_p2 + zext_ln153_5_fu_528_p1);

assign add_ln153_7_fu_571_p2 = (tmp_14_fu_563_p3 + zext_ln147_fu_294_p1);

assign add_ln153_fu_472_p2 = (mul_ln153_fu_406_p2 + zext_ln153_2_fu_468_p1);

assign add_ln157_1_fu_454_p2 = (tmp_7_fu_446_p3 + zext_ln147_1_fu_298_p1);

assign add_ln157_fu_440_p2 = (sub_ln157_fu_380_p2 + zext_ln157_1_fu_436_p1);

assign and_ln147_fu_327_p2 = (xor_ln147_fu_316_p2 & icmp_ln149_fu_321_p2);

assign and_ln154_1_fu_722_p2 = (or_ln154_2_fu_716_p2 & or_ln154_1_fu_698_p2);

assign and_ln154_2_fu_728_p2 = (grp_fu_869_p_dout0 & and_ln154_1_fu_722_p2);

assign and_ln154_3_fu_810_p2 = (or_ln154_4_fu_804_p2 & or_ln154_3_fu_786_p2);

assign and_ln154_4_fu_816_p2 = (grp_fu_873_p_dout0 & and_ln154_3_fu_810_p2);

assign and_ln154_5_fu_902_p2 = (or_ln154_6_fu_896_p2 & or_ln154_5_fu_878_p2);

assign and_ln154_6_fu_908_p2 = (grp_fu_877_p_dout0 & and_ln154_5_fu_902_p2);

assign and_ln154_fu_638_p2 = (or_ln154_fu_632_p2 & grp_fu_865_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln154_1_fu_652_p1 = layer2_conv_load_1_reg_1002_pp0_iter3_reg;

assign bitcast_ln154_2_fu_669_p1 = select_ln154_reg_1023;

assign bitcast_ln154_3_fu_740_p1 = layer2_conv_load_2_reg_1009_pp0_iter5_reg;

assign bitcast_ln154_4_fu_757_p1 = select_ln154_1_reg_1030_pp0_iter5_reg;

assign bitcast_ln154_5_fu_832_p1 = layer2_conv_load_3_reg_1016_pp0_iter7_reg;

assign bitcast_ln154_6_fu_849_p1 = select_ln154_2_reg_1037_pp0_iter7_reg;

assign bitcast_ln154_fu_603_p1 = layer2_conv_load_reg_995;

assign empty_fu_262_p2 = (tmp_s_fu_254_p3 | 5'd1);

assign grp_fu_865_p_ce = 1'b1;

assign grp_fu_865_p_din0 = layer2_conv_q3;

assign grp_fu_865_p_din1 = 32'd3463342888;

assign grp_fu_865_p_opcode = 5'd2;

assign grp_fu_869_p_ce = 1'b1;

assign grp_fu_869_p_din0 = layer2_conv_load_1_reg_1002;

assign grp_fu_869_p_din1 = select_ln154_fu_644_p3;

assign grp_fu_869_p_opcode = 5'd2;

assign grp_fu_873_p_ce = 1'b1;

assign grp_fu_873_p_din0 = layer2_conv_load_2_reg_1009_pp0_iter4_reg;

assign grp_fu_873_p_din1 = select_ln154_1_reg_1030;

assign grp_fu_873_p_opcode = 5'd2;

assign grp_fu_877_p_ce = 1'b1;

assign grp_fu_877_p_din0 = layer2_conv_load_3_reg_1016_pp0_iter6_reg;

assign grp_fu_877_p_din1 = select_ln154_2_reg_1037;

assign grp_fu_877_p_opcode = 5'd2;

assign icmp_ln147_fu_206_p2 = ((ap_sig_allocacmp_indvar_flatten148_load == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_221_p2 = ((ap_sig_allocacmp_indvar_flatten124_load == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_321_p2 = ((c_fu_78 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln154_10_fu_866_p2 = ((tmp_21_fu_835_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln154_11_fu_872_p2 = ((trunc_ln154_5_fu_845_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_12_fu_884_p2 = ((tmp_22_fu_852_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln154_13_fu_890_p2 = ((trunc_ln154_6_fu_862_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_1_fu_626_p2 = ((trunc_ln154_fu_616_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_2_fu_686_p2 = ((tmp_15_fu_655_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln154_3_fu_692_p2 = ((trunc_ln154_1_fu_665_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_4_fu_704_p2 = ((tmp_16_fu_672_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln154_5_fu_710_p2 = ((trunc_ln154_2_fu_682_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_6_fu_774_p2 = ((tmp_18_fu_743_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln154_7_fu_780_p2 = ((trunc_ln154_3_fu_753_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_8_fu_792_p2 = ((tmp_19_fu_760_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln154_9_fu_798_p2 = ((trunc_ln154_4_fu_770_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_620_p2 = ((tmp_11_fu_606_p4 != 8'd255) ? 1'b1 : 1'b0);

assign layer2_conv_address0 = zext_ln153_7_fu_577_p1;

assign layer2_conv_address1 = zext_ln153_4_fu_517_p1;

assign layer2_conv_address2 = zext_ln153_6_fu_552_p1;

assign layer2_conv_address3 = zext_ln153_3_fu_492_p1;

assign layer2_pool_address0 = zext_ln157_2_fu_828_p1;

assign layer2_pool_d0 = ((and_ln154_6_fu_908_p2[0:0] == 1'b1) ? layer2_conv_load_3_reg_1016_pp0_iter7_reg : select_ln154_2_reg_1037_pp0_iter7_reg);

assign mul_ln153_1_fu_430_p0 = mul_ln153_1_fu_430_p00;

assign mul_ln153_1_fu_430_p00 = select_ln148_3_fu_418_p3;

assign mul_ln153_1_fu_430_p1 = 10'd29;

assign mul_ln153_fu_406_p0 = mul_ln153_fu_406_p00;

assign mul_ln153_fu_406_p00 = select_ln148_2_fu_394_p3;

assign mul_ln153_fu_406_p1 = 10'd29;

assign or_ln148_fu_339_p2 = (icmp_ln148_reg_960 | and_ln147_fu_327_p2);

assign or_ln153_fu_522_p2 = (tmp_8_fu_460_p3 | 5'd1);

assign or_ln154_1_fu_698_p2 = (icmp_ln154_3_fu_692_p2 | icmp_ln154_2_fu_686_p2);

assign or_ln154_2_fu_716_p2 = (icmp_ln154_5_fu_710_p2 | icmp_ln154_4_fu_704_p2);

assign or_ln154_3_fu_786_p2 = (icmp_ln154_7_fu_780_p2 | icmp_ln154_6_fu_774_p2);

assign or_ln154_4_fu_804_p2 = (icmp_ln154_9_fu_798_p2 | icmp_ln154_8_fu_792_p2);

assign or_ln154_5_fu_878_p2 = (icmp_ln154_11_fu_872_p2 | icmp_ln154_10_fu_866_p2);

assign or_ln154_6_fu_896_p2 = (icmp_ln154_13_fu_890_p2 | icmp_ln154_12_fu_884_p2);

assign or_ln154_fu_632_p2 = (icmp_ln154_fu_620_p2 | icmp_ln154_1_fu_626_p2);

assign p_mid1122_fu_412_p2 = (p_mid2_fu_386_p3 | 5'd1);

assign p_mid2_fu_386_p3 = {{add_ln148_fu_333_p2}, {1'd0}};

assign select_ln147_1_fu_287_p3 = ((icmp_ln148_reg_960[0:0] == 1'b1) ? add_ln147_fu_274_p2 : f_fu_90);

assign select_ln147_2_fu_302_p3 = ((icmp_ln148_reg_960[0:0] == 1'b1) ? 5'd0 : tmp_s_fu_254_p3);

assign select_ln147_3_fu_309_p3 = ((icmp_ln148_reg_960[0:0] == 1'b1) ? 5'd1 : empty_fu_262_p2);

assign select_ln147_fu_280_p3 = ((icmp_ln148_reg_960[0:0] == 1'b1) ? 4'd0 : r_fu_82);

assign select_ln148_1_fu_352_p3 = ((and_ln147_fu_327_p2[0:0] == 1'b1) ? add_ln148_fu_333_p2 : select_ln147_fu_280_p3);

assign select_ln148_2_fu_394_p3 = ((and_ln147_fu_327_p2[0:0] == 1'b1) ? p_mid2_fu_386_p3 : select_ln147_2_fu_302_p3);

assign select_ln148_3_fu_418_p3 = ((and_ln147_fu_327_p2[0:0] == 1'b1) ? p_mid1122_fu_412_p2 : select_ln147_3_fu_309_p3);

assign select_ln148_4_fu_233_p3 = ((icmp_ln148_fu_221_p2[0:0] == 1'b1) ? 8'd1 : add_ln148_1_fu_227_p2);

assign select_ln148_fu_344_p3 = ((or_ln148_fu_339_p2[0:0] == 1'b1) ? 4'd0 : c_fu_78);

assign select_ln154_1_fu_734_p3 = ((and_ln154_2_fu_728_p2[0:0] == 1'b1) ? layer2_conv_load_1_reg_1002_pp0_iter3_reg : select_ln154_reg_1023);

assign select_ln154_2_fu_822_p3 = ((and_ln154_4_fu_816_p2[0:0] == 1'b1) ? layer2_conv_load_2_reg_1009_pp0_iter5_reg : select_ln154_1_reg_1030_pp0_iter5_reg);

assign select_ln154_fu_644_p3 = ((and_ln154_fu_638_p2[0:0] == 1'b1) ? layer2_conv_load_reg_995 : 32'd3463342888);

assign sub_ln157_fu_380_p2 = (tmp_fu_360_p3 - zext_ln157_fu_376_p1);

assign tmp_10_fu_503_p3 = {{add_ln153_2_fu_497_p2}, {3'd0}};

assign tmp_11_fu_606_p4 = {{bitcast_ln154_fu_603_p1[30:23]}};

assign tmp_13_fu_538_p3 = {{add_ln153_4_fu_532_p2}, {3'd0}};

assign tmp_14_fu_563_p3 = {{add_ln153_6_fu_557_p2}, {3'd0}};

assign tmp_15_fu_655_p4 = {{bitcast_ln154_1_fu_652_p1[30:23]}};

assign tmp_16_fu_672_p4 = {{bitcast_ln154_2_fu_669_p1[30:23]}};

assign tmp_18_fu_743_p4 = {{bitcast_ln154_3_fu_740_p1[30:23]}};

assign tmp_19_fu_760_p4 = {{bitcast_ln154_4_fu_757_p1[30:23]}};

assign tmp_1_fu_368_p3 = {{select_ln148_1_fu_352_p3}, {1'd0}};

assign tmp_21_fu_835_p4 = {{bitcast_ln154_5_fu_832_p1[30:23]}};

assign tmp_22_fu_852_p4 = {{bitcast_ln154_6_fu_849_p1[30:23]}};

assign tmp_7_fu_446_p3 = {{add_ln157_fu_440_p2}, {3'd0}};

assign tmp_8_fu_460_p3 = {{select_ln148_fu_344_p3}, {1'd0}};

assign tmp_9_fu_478_p3 = {{add_ln153_fu_472_p2}, {3'd0}};

assign tmp_fu_360_p3 = {{select_ln148_1_fu_352_p3}, {4'd0}};

assign tmp_s_fu_254_p3 = {{r_fu_82}, {1'd0}};

assign trunc_ln154_1_fu_665_p1 = bitcast_ln154_1_fu_652_p1[22:0];

assign trunc_ln154_2_fu_682_p1 = bitcast_ln154_2_fu_669_p1[22:0];

assign trunc_ln154_3_fu_753_p1 = bitcast_ln154_3_fu_740_p1[22:0];

assign trunc_ln154_4_fu_770_p1 = bitcast_ln154_4_fu_757_p1[22:0];

assign trunc_ln154_5_fu_845_p1 = bitcast_ln154_5_fu_832_p1[22:0];

assign trunc_ln154_6_fu_862_p1 = bitcast_ln154_6_fu_849_p1[22:0];

assign trunc_ln154_fu_616_p1 = bitcast_ln154_fu_603_p1[22:0];

assign xor_ln147_fu_316_p2 = (icmp_ln148_reg_960 ^ 1'd1);

assign zext_ln147_1_fu_298_p1 = select_ln147_1_fu_287_p3;

assign zext_ln147_fu_294_p1 = select_ln147_1_fu_287_p3;

assign zext_ln153_2_fu_468_p1 = tmp_8_fu_460_p3;

assign zext_ln153_3_fu_492_p1 = add_ln153_1_fu_486_p2;

assign zext_ln153_4_fu_517_p1 = add_ln153_3_fu_511_p2;

assign zext_ln153_5_fu_528_p1 = or_ln153_fu_522_p2;

assign zext_ln153_6_fu_552_p1 = add_ln153_5_fu_546_p2;

assign zext_ln153_7_fu_577_p1 = add_ln153_7_fu_571_p2;

assign zext_ln157_1_fu_436_p1 = select_ln148_fu_344_p3;

assign zext_ln157_2_fu_828_p1 = add_ln157_1_reg_970_pp0_iter7_reg;

assign zext_ln157_fu_376_p1 = tmp_1_fu_368_p3;

endmodule //cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_147_17_VITIS_LOOP_148_18_VITIS_LOOP_149_19
