// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_167_22_VITIS_LOOP_168_23_VITIS_LOOP_169_24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_pool_address0,
        layer2_pool_ce0,
        layer2_pool_q0,
        flat_address0,
        flat_ce0,
        flat_we0,
        flat_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] layer2_pool_address0;
output   layer2_pool_ce0;
input  [31:0] layer2_pool_q0;
output  [10:0] flat_address0;
output   flat_ce0;
output   flat_we0;
output  [31:0] flat_d0;

reg ap_idle;
reg layer2_pool_ce0;
reg flat_ce0;
reg flat_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln167_fu_164_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln168_fu_194_p2;
reg   [0:0] icmp_ln168_reg_507;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln167_fu_254_p2;
reg   [0:0] and_ln167_reg_514;
wire   [63:0] zext_ln170_3_fu_316_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] idx_1_cast_fu_422_p1;
reg   [3:0] f_fu_62;
wire   [3:0] add_ln169_fu_321_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_f_load;
reg   [10:0] idx_1_fu_66;
wire   [10:0] add_ln170_fu_427_p2;
reg   [3:0] c_fu_70;
wire   [3:0] select_ln168_2_fu_280_p3;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [10:0] idx_fu_74;
wire   [10:0] select_ln168_3_fu_415_p3;
reg   [7:0] indvar_flatten155_fu_78;
wire   [7:0] select_ln168_4_fu_333_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten155_load;
reg   [3:0] r_fu_82;
wire   [3:0] select_ln167_3_fu_208_p3;
reg   [3:0] ap_sig_allocacmp_r_load;
reg   [10:0] indvars_iv189_fu_86;
wire   [10:0] select_ln167_4_fu_395_p3;
reg   [10:0] indvar_flatten171_fu_90;
wire   [10:0] add_ln167_2_fu_170_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten171_load;
wire   [3:0] add_ln167_fu_188_p2;
wire   [4:0] tmp_5_fu_224_p3;
wire   [7:0] tmp_s_fu_216_p3;
wire   [7:0] zext_ln170_fu_232_p1;
wire   [0:0] icmp_ln169_fu_248_p2;
wire   [0:0] xor_ln167_fu_242_p2;
wire   [3:0] select_ln167_1_fu_200_p3;
wire   [0:0] or_ln168_fu_266_p2;
wire   [3:0] add_ln168_fu_260_p2;
wire   [7:0] sub_ln170_fu_236_p2;
wire   [7:0] zext_ln170_1_fu_288_p1;
wire   [7:0] add_ln170_1_fu_292_p2;
wire   [3:0] select_ln168_1_fu_272_p3;
wire   [10:0] tmp_6_fu_298_p3;
wire   [10:0] zext_ln170_2_fu_306_p1;
wire   [10:0] add_ln170_2_fu_310_p2;
wire   [7:0] add_ln168_2_fu_327_p2;
wire   [10:0] add_ln167_1_fu_375_p2;
wire   [10:0] select_ln167_fu_381_p3;
wire   [10:0] add_ln168_1_fu_402_p2;
wire   [10:0] select_ln167_2_fu_388_p3;
wire   [10:0] select_ln168_fu_408_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln167_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_70 <= select_ln168_2_fu_280_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_70 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln167_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            f_fu_62 <= add_ln169_fu_321_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            f_fu_62 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_1_fu_66 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            idx_1_fu_66 <= add_ln170_fu_427_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            idx_fu_74 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            idx_fu_74 <= select_ln168_3_fu_415_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln167_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten155_fu_78 <= select_ln168_4_fu_333_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten155_fu_78 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln167_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten171_fu_90 <= add_ln167_2_fu_170_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten171_fu_90 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvars_iv189_fu_86 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvars_iv189_fu_86 <= select_ln167_4_fu_395_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln167_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_82 <= select_ln167_3_fu_208_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_82 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln167_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln167_reg_514 <= and_ln167_fu_254_p2;
        icmp_ln168_reg_507 <= icmp_ln168_fu_194_p2;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_164_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_70;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_f_load = 4'd0;
    end else begin
        ap_sig_allocacmp_f_load = f_fu_62;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten155_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten155_load = indvar_flatten155_fu_78;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten171_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten171_load = indvar_flatten171_fu_90;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_load = 4'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flat_ce0 = 1'b1;
    end else begin
        flat_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        flat_we0 = 1'b1;
    end else begin
        flat_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_pool_ce0 = 1'b1;
    end else begin
        layer2_pool_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln167_1_fu_375_p2 = (indvars_iv189_fu_86 + 11'd112);

assign add_ln167_2_fu_170_p2 = (ap_sig_allocacmp_indvar_flatten171_load + 11'd1);

assign add_ln167_fu_188_p2 = (ap_sig_allocacmp_r_load + 4'd1);

assign add_ln168_1_fu_402_p2 = (select_ln167_fu_381_p3 + 11'd8);

assign add_ln168_2_fu_327_p2 = (ap_sig_allocacmp_indvar_flatten155_load + 8'd1);

assign add_ln168_fu_260_p2 = (select_ln167_1_fu_200_p3 + 4'd1);

assign add_ln169_fu_321_p2 = (select_ln168_1_fu_272_p3 + 4'd1);

assign add_ln170_1_fu_292_p2 = (sub_ln170_fu_236_p2 + zext_ln170_1_fu_288_p1);

assign add_ln170_2_fu_310_p2 = (tmp_6_fu_298_p3 + zext_ln170_2_fu_306_p1);

assign add_ln170_fu_427_p2 = (select_ln168_fu_408_p3 + 11'd1);

assign and_ln167_fu_254_p2 = (xor_ln167_fu_242_p2 & icmp_ln169_fu_248_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign flat_address0 = idx_1_cast_fu_422_p1;

assign flat_d0 = layer2_pool_q0;

assign icmp_ln167_fu_164_p2 = ((ap_sig_allocacmp_indvar_flatten171_load == 11'd1568) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_194_p2 = ((ap_sig_allocacmp_indvar_flatten155_load == 8'd112) ? 1'b1 : 1'b0);

assign icmp_ln169_fu_248_p2 = ((ap_sig_allocacmp_f_load == 4'd8) ? 1'b1 : 1'b0);

assign idx_1_cast_fu_422_p1 = select_ln168_fu_408_p3;

assign layer2_pool_address0 = zext_ln170_3_fu_316_p1;

assign or_ln168_fu_266_p2 = (icmp_ln168_fu_194_p2 | and_ln167_fu_254_p2);

assign select_ln167_1_fu_200_p3 = ((icmp_ln168_fu_194_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_c_load);

assign select_ln167_2_fu_388_p3 = ((icmp_ln168_reg_507[0:0] == 1'b1) ? add_ln167_1_fu_375_p2 : idx_1_fu_66);

assign select_ln167_3_fu_208_p3 = ((icmp_ln168_fu_194_p2[0:0] == 1'b1) ? add_ln167_fu_188_p2 : ap_sig_allocacmp_r_load);

assign select_ln167_4_fu_395_p3 = ((icmp_ln168_reg_507[0:0] == 1'b1) ? add_ln167_1_fu_375_p2 : indvars_iv189_fu_86);

assign select_ln167_fu_381_p3 = ((icmp_ln168_reg_507[0:0] == 1'b1) ? add_ln167_1_fu_375_p2 : idx_fu_74);

assign select_ln168_1_fu_272_p3 = ((or_ln168_fu_266_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_f_load);

assign select_ln168_2_fu_280_p3 = ((and_ln167_fu_254_p2[0:0] == 1'b1) ? add_ln168_fu_260_p2 : select_ln167_1_fu_200_p3);

assign select_ln168_3_fu_415_p3 = ((and_ln167_reg_514[0:0] == 1'b1) ? add_ln168_1_fu_402_p2 : select_ln167_fu_381_p3);

assign select_ln168_4_fu_333_p3 = ((icmp_ln168_fu_194_p2[0:0] == 1'b1) ? 8'd1 : add_ln168_2_fu_327_p2);

assign select_ln168_fu_408_p3 = ((and_ln167_reg_514[0:0] == 1'b1) ? add_ln168_1_fu_402_p2 : select_ln167_2_fu_388_p3);

assign sub_ln170_fu_236_p2 = (tmp_s_fu_216_p3 - zext_ln170_fu_232_p1);

assign tmp_5_fu_224_p3 = {{select_ln167_3_fu_208_p3}, {1'd0}};

assign tmp_6_fu_298_p3 = {{add_ln170_1_fu_292_p2}, {3'd0}};

assign tmp_s_fu_216_p3 = {{select_ln167_3_fu_208_p3}, {4'd0}};

assign xor_ln167_fu_242_p2 = (icmp_ln168_fu_194_p2 ^ 1'd1);

assign zext_ln170_1_fu_288_p1 = select_ln168_2_fu_280_p3;

assign zext_ln170_2_fu_306_p1 = select_ln168_1_fu_272_p3;

assign zext_ln170_3_fu_316_p1 = add_ln170_2_fu_310_p2;

assign zext_ln170_fu_232_p1 = tmp_5_fu_224_p3;

endmodule //cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_167_22_VITIS_LOOP_168_23_VITIS_LOOP_169_24
