// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_103_6_VITIS_LOOP_104_7_VITIS_LOOP_105_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer1_pool_address0,
        layer1_pool_ce0,
        layer1_pool_we0,
        layer1_pool_d0,
        layer1_conv_address0,
        layer1_conv_ce0,
        layer1_conv_q0,
        layer1_conv_address1,
        layer1_conv_ce1,
        layer1_conv_q1,
        layer1_conv_address2,
        layer1_conv_ce2,
        layer1_conv_q2,
        layer1_conv_address3,
        layer1_conv_ce3,
        layer1_conv_q3,
        grp_fu_865_p_din0,
        grp_fu_865_p_din1,
        grp_fu_865_p_opcode,
        grp_fu_865_p_dout0,
        grp_fu_865_p_ce,
        grp_fu_869_p_din0,
        grp_fu_869_p_din1,
        grp_fu_869_p_opcode,
        grp_fu_869_p_dout0,
        grp_fu_869_p_ce,
        grp_fu_873_p_din0,
        grp_fu_873_p_din1,
        grp_fu_873_p_opcode,
        grp_fu_873_p_dout0,
        grp_fu_873_p_ce,
        grp_fu_877_p_din0,
        grp_fu_877_p_din1,
        grp_fu_877_p_opcode,
        grp_fu_877_p_dout0,
        grp_fu_877_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] layer1_pool_address0;
output   layer1_pool_ce0;
output   layer1_pool_we0;
output  [31:0] layer1_pool_d0;
output  [13:0] layer1_conv_address0;
output   layer1_conv_ce0;
input  [31:0] layer1_conv_q0;
output  [13:0] layer1_conv_address1;
output   layer1_conv_ce1;
input  [31:0] layer1_conv_q1;
output  [13:0] layer1_conv_address2;
output   layer1_conv_ce2;
input  [31:0] layer1_conv_q2;
output  [13:0] layer1_conv_address3;
output   layer1_conv_ce3;
input  [31:0] layer1_conv_q3;
output  [31:0] grp_fu_865_p_din0;
output  [31:0] grp_fu_865_p_din1;
output  [4:0] grp_fu_865_p_opcode;
input  [0:0] grp_fu_865_p_dout0;
output   grp_fu_865_p_ce;
output  [31:0] grp_fu_869_p_din0;
output  [31:0] grp_fu_869_p_din1;
output  [4:0] grp_fu_869_p_opcode;
input  [0:0] grp_fu_869_p_dout0;
output   grp_fu_869_p_ce;
output  [31:0] grp_fu_873_p_din0;
output  [31:0] grp_fu_873_p_din1;
output  [4:0] grp_fu_873_p_opcode;
input  [0:0] grp_fu_873_p_dout0;
output   grp_fu_873_p_ce;
output  [31:0] grp_fu_877_p_din0;
output  [31:0] grp_fu_877_p_din1;
output  [4:0] grp_fu_877_p_opcode;
input  [0:0] grp_fu_877_p_dout0;
output   grp_fu_877_p_ce;

reg ap_idle;
reg layer1_pool_ce0;
reg layer1_pool_we0;
reg layer1_conv_ce0;
reg layer1_conv_ce1;
reg layer1_conv_ce2;
reg layer1_conv_ce3;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln103_fu_235_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [11:0] add_ln113_1_fu_480_p2;
reg   [11:0] add_ln113_1_reg_1030;
reg   [11:0] add_ln113_1_reg_1030_pp0_iter2_reg;
reg   [11:0] add_ln113_1_reg_1030_pp0_iter3_reg;
reg   [11:0] add_ln113_1_reg_1030_pp0_iter4_reg;
reg   [11:0] add_ln113_1_reg_1030_pp0_iter5_reg;
reg   [11:0] add_ln113_1_reg_1030_pp0_iter6_reg;
reg   [11:0] add_ln113_1_reg_1030_pp0_iter7_reg;
reg   [31:0] layer1_conv_load_reg_1055;
reg   [31:0] layer1_conv_load_1_reg_1062;
reg   [31:0] layer1_conv_load_1_reg_1062_pp0_iter3_reg;
reg   [31:0] layer1_conv_load_2_reg_1069;
reg   [31:0] layer1_conv_load_2_reg_1069_pp0_iter3_reg;
reg   [31:0] layer1_conv_load_2_reg_1069_pp0_iter4_reg;
reg   [31:0] layer1_conv_load_2_reg_1069_pp0_iter5_reg;
reg   [31:0] layer1_conv_load_3_reg_1076;
reg   [31:0] layer1_conv_load_3_reg_1076_pp0_iter3_reg;
reg   [31:0] layer1_conv_load_3_reg_1076_pp0_iter4_reg;
reg   [31:0] layer1_conv_load_3_reg_1076_pp0_iter5_reg;
reg   [31:0] layer1_conv_load_3_reg_1076_pp0_iter6_reg;
reg   [31:0] layer1_conv_load_3_reg_1076_pp0_iter7_reg;
wire   [31:0] select_ln110_fu_714_p3;
reg   [31:0] select_ln110_reg_1083;
wire   [31:0] select_ln110_1_fu_804_p3;
reg   [31:0] select_ln110_1_reg_1090;
reg   [31:0] select_ln110_1_reg_1090_pp0_iter5_reg;
wire   [31:0] select_ln110_2_fu_892_p3;
reg   [31:0] select_ln110_2_reg_1097;
reg   [31:0] select_ln110_2_reg_1097_pp0_iter7_reg;
wire   [63:0] zext_ln109_5_fu_522_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln109_6_fu_551_p1;
wire   [63:0] zext_ln109_8_fu_590_p1;
wire   [63:0] zext_ln109_10_fu_623_p1;
wire   [63:0] zext_ln113_2_fu_898_p1;
reg   [4:0] c_fu_90;
wire   [4:0] add_ln105_fu_628_p2;
wire    ap_loop_init;
reg   [4:0] r_1_fu_94;
wire   [4:0] select_ln104_1_fu_346_p3;
reg   [9:0] indvar_flatten15_fu_98;
wire   [9:0] select_ln104_4_fu_640_p3;
reg   [2:0] f_fu_102;
wire   [2:0] select_ln103_1_fu_276_p3;
reg   [11:0] indvar_flatten39_fu_106;
wire   [11:0] add_ln103_1_fu_241_p2;
wire   [5:0] tmp_29_fu_221_p3;
wire   [0:0] icmp_ln104_fu_262_p2;
wire   [2:0] add_ln103_fu_256_p2;
wire   [5:0] empty_fu_229_p2;
wire   [0:0] icmp_ln105_fu_314_p2;
wire   [0:0] xor_ln103_fu_308_p2;
wire   [4:0] select_ln103_fu_268_p3;
wire   [0:0] and_ln103_fu_320_p2;
wire   [0:0] or_ln104_fu_332_p2;
wire   [4:0] add_ln104_fu_326_p2;
wire   [9:0] tmp_fu_358_p3;
wire   [9:0] zext_ln113_fu_354_p1;
wire   [5:0] p_mid_fu_372_p3;
wire   [5:0] select_ln103_2_fu_292_p3;
wire   [5:0] select_ln104_2_fu_380_p3;
wire   [11:0] tmp_13_fu_388_p3;
wire   [6:0] tmp_14_fu_400_p3;
wire   [61:0] zext_ln109_fu_396_p1;
wire   [61:0] zext_ln109_1_fu_408_p1;
wire   [5:0] p_mid113_fu_418_p2;
wire   [5:0] select_ln103_3_fu_300_p3;
wire   [5:0] select_ln104_3_fu_424_p3;
wire   [11:0] tmp_15_fu_432_p3;
wire   [6:0] tmp_16_fu_444_p3;
wire   [61:0] zext_ln109_2_fu_440_p1;
wire   [61:0] zext_ln109_3_fu_452_p1;
wire   [4:0] select_ln104_fu_338_p3;
wire   [9:0] sub_ln113_fu_366_p2;
wire   [9:0] zext_ln113_1_fu_462_p1;
wire   [9:0] add_ln113_fu_466_p2;
wire   [11:0] tmp_33_fu_472_p3;
wire   [11:0] zext_ln103_1_fu_288_p1;
wire   [5:0] tmp_34_fu_486_p3;
wire   [61:0] sub_ln109_fu_412_p2;
wire   [61:0] zext_ln109_4_fu_494_p1;
wire   [61:0] add_ln109_fu_498_p2;
wire   [10:0] tmp_40_cast_fu_504_p4;
wire   [13:0] tmp_35_fu_514_p3;
wire   [61:0] sub_ln109_1_fu_456_p2;
wire   [61:0] add_ln109_1_fu_527_p2;
wire   [10:0] tmp_44_cast_fu_533_p4;
wire   [13:0] tmp_36_fu_543_p3;
wire   [5:0] or_ln109_fu_556_p2;
wire   [11:0] trunc_ln109_fu_562_p1;
wire   [11:0] zext_ln109_7_fu_566_p1;
wire   [11:0] add_ln109_2_fu_570_p2;
wire   [13:0] tmp_37_fu_576_p3;
wire   [13:0] zext_ln103_fu_284_p1;
wire   [13:0] add_ln109_3_fu_584_p2;
wire   [11:0] trunc_ln109_1_fu_595_p1;
wire   [11:0] zext_ln109_9_fu_599_p1;
wire   [11:0] add_ln109_4_fu_603_p2;
wire   [13:0] tmp_38_fu_609_p3;
wire   [13:0] add_ln109_5_fu_617_p2;
wire   [9:0] add_ln104_1_fu_634_p2;
wire   [31:0] bitcast_ln110_fu_673_p1;
wire   [7:0] tmp_3_fu_676_p4;
wire   [22:0] trunc_ln110_fu_686_p1;
wire   [0:0] icmp_ln110_1_fu_696_p2;
wire   [0:0] icmp_ln110_fu_690_p2;
wire   [0:0] or_ln110_fu_702_p2;
wire   [0:0] and_ln110_fu_708_p2;
wire   [31:0] bitcast_ln110_1_fu_722_p1;
wire   [31:0] bitcast_ln110_2_fu_739_p1;
wire   [7:0] tmp_5_fu_725_p4;
wire   [22:0] trunc_ln110_1_fu_735_p1;
wire   [0:0] icmp_ln110_3_fu_762_p2;
wire   [0:0] icmp_ln110_2_fu_756_p2;
wire   [7:0] tmp_6_fu_742_p4;
wire   [22:0] trunc_ln110_2_fu_752_p1;
wire   [0:0] icmp_ln110_5_fu_780_p2;
wire   [0:0] icmp_ln110_4_fu_774_p2;
wire   [0:0] or_ln110_1_fu_768_p2;
wire   [0:0] or_ln110_2_fu_786_p2;
wire   [0:0] and_ln110_1_fu_792_p2;
wire   [0:0] and_ln110_2_fu_798_p2;
wire   [31:0] bitcast_ln110_3_fu_810_p1;
wire   [31:0] bitcast_ln110_4_fu_827_p1;
wire   [7:0] tmp_8_fu_813_p4;
wire   [22:0] trunc_ln110_3_fu_823_p1;
wire   [0:0] icmp_ln110_7_fu_850_p2;
wire   [0:0] icmp_ln110_6_fu_844_p2;
wire   [7:0] tmp_9_fu_830_p4;
wire   [22:0] trunc_ln110_4_fu_840_p1;
wire   [0:0] icmp_ln110_9_fu_868_p2;
wire   [0:0] icmp_ln110_8_fu_862_p2;
wire   [0:0] or_ln110_3_fu_856_p2;
wire   [0:0] or_ln110_4_fu_874_p2;
wire   [0:0] and_ln110_3_fu_880_p2;
wire   [0:0] and_ln110_4_fu_886_p2;
wire   [31:0] bitcast_ln110_5_fu_902_p1;
wire   [31:0] bitcast_ln110_6_fu_919_p1;
wire   [7:0] tmp_10_fu_905_p4;
wire   [22:0] trunc_ln110_5_fu_915_p1;
wire   [0:0] icmp_ln110_11_fu_942_p2;
wire   [0:0] icmp_ln110_10_fu_936_p2;
wire   [7:0] tmp_11_fu_922_p4;
wire   [22:0] trunc_ln110_6_fu_932_p1;
wire   [0:0] icmp_ln110_13_fu_960_p2;
wire   [0:0] icmp_ln110_12_fu_954_p2;
wire   [0:0] or_ln110_5_fu_948_p2;
wire   [0:0] or_ln110_6_fu_966_p2;
wire   [0:0] and_ln110_5_fu_972_p2;
wire   [0:0] and_ln110_6_fu_978_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cnn_predict_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_90 <= 5'd0;
        end else if (((icmp_ln103_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_90 <= add_ln105_fu_628_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            f_fu_102 <= 3'd0;
        end else if (((icmp_ln103_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            f_fu_102 <= select_ln103_1_fu_276_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten15_fu_98 <= 10'd0;
        end else if (((icmp_ln103_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten15_fu_98 <= select_ln104_4_fu_640_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten39_fu_106 <= 12'd0;
        end else if (((icmp_ln103_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten39_fu_106 <= add_ln103_1_fu_241_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_1_fu_94 <= 5'd0;
        end else if (((icmp_ln103_fu_235_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            r_1_fu_94 <= select_ln104_1_fu_346_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_235_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln113_1_reg_1030 <= add_ln113_1_fu_480_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln113_1_reg_1030_pp0_iter2_reg <= add_ln113_1_reg_1030;
        add_ln113_1_reg_1030_pp0_iter3_reg <= add_ln113_1_reg_1030_pp0_iter2_reg;
        add_ln113_1_reg_1030_pp0_iter4_reg <= add_ln113_1_reg_1030_pp0_iter3_reg;
        add_ln113_1_reg_1030_pp0_iter5_reg <= add_ln113_1_reg_1030_pp0_iter4_reg;
        add_ln113_1_reg_1030_pp0_iter6_reg <= add_ln113_1_reg_1030_pp0_iter5_reg;
        add_ln113_1_reg_1030_pp0_iter7_reg <= add_ln113_1_reg_1030_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        layer1_conv_load_1_reg_1062_pp0_iter3_reg <= layer1_conv_load_1_reg_1062;
        layer1_conv_load_2_reg_1069_pp0_iter3_reg <= layer1_conv_load_2_reg_1069;
        layer1_conv_load_2_reg_1069_pp0_iter4_reg <= layer1_conv_load_2_reg_1069_pp0_iter3_reg;
        layer1_conv_load_2_reg_1069_pp0_iter5_reg <= layer1_conv_load_2_reg_1069_pp0_iter4_reg;
        layer1_conv_load_3_reg_1076_pp0_iter3_reg <= layer1_conv_load_3_reg_1076;
        layer1_conv_load_3_reg_1076_pp0_iter4_reg <= layer1_conv_load_3_reg_1076_pp0_iter3_reg;
        layer1_conv_load_3_reg_1076_pp0_iter5_reg <= layer1_conv_load_3_reg_1076_pp0_iter4_reg;
        layer1_conv_load_3_reg_1076_pp0_iter6_reg <= layer1_conv_load_3_reg_1076_pp0_iter5_reg;
        layer1_conv_load_3_reg_1076_pp0_iter7_reg <= layer1_conv_load_3_reg_1076_pp0_iter6_reg;
        select_ln110_1_reg_1090 <= select_ln110_1_fu_804_p3;
        select_ln110_1_reg_1090_pp0_iter5_reg <= select_ln110_1_reg_1090;
        select_ln110_2_reg_1097 <= select_ln110_2_fu_892_p3;
        select_ln110_2_reg_1097_pp0_iter7_reg <= select_ln110_2_reg_1097;
        select_ln110_reg_1083 <= select_ln110_fu_714_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer1_conv_load_1_reg_1062 <= layer1_conv_q2;
        layer1_conv_load_2_reg_1069 <= layer1_conv_q1;
        layer1_conv_load_3_reg_1076 <= layer1_conv_q0;
        layer1_conv_load_reg_1055 <= layer1_conv_q3;
    end
end

always @ (*) begin
    if (((icmp_ln103_fu_235_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer1_conv_ce0 = 1'b1;
    end else begin
        layer1_conv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer1_conv_ce1 = 1'b1;
    end else begin
        layer1_conv_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer1_conv_ce2 = 1'b1;
    end else begin
        layer1_conv_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer1_conv_ce3 = 1'b1;
    end else begin
        layer1_conv_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer1_pool_ce0 = 1'b1;
    end else begin
        layer1_pool_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        layer1_pool_we0 = 1'b1;
    end else begin
        layer1_pool_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_1_fu_241_p2 = (indvar_flatten39_fu_106 + 12'd1);

assign add_ln103_fu_256_p2 = (f_fu_102 + 3'd1);

assign add_ln104_1_fu_634_p2 = (indvar_flatten15_fu_98 + 10'd1);

assign add_ln104_fu_326_p2 = (select_ln103_fu_268_p3 + 5'd1);

assign add_ln105_fu_628_p2 = (select_ln104_fu_338_p3 + 5'd1);

assign add_ln109_1_fu_527_p2 = (sub_ln109_1_fu_456_p2 + zext_ln109_4_fu_494_p1);

assign add_ln109_2_fu_570_p2 = (trunc_ln109_fu_562_p1 + zext_ln109_7_fu_566_p1);

assign add_ln109_3_fu_584_p2 = (tmp_37_fu_576_p3 + zext_ln103_fu_284_p1);

assign add_ln109_4_fu_603_p2 = (trunc_ln109_1_fu_595_p1 + zext_ln109_9_fu_599_p1);

assign add_ln109_5_fu_617_p2 = (tmp_38_fu_609_p3 + zext_ln103_fu_284_p1);

assign add_ln109_fu_498_p2 = (sub_ln109_fu_412_p2 + zext_ln109_4_fu_494_p1);

assign add_ln113_1_fu_480_p2 = (tmp_33_fu_472_p3 + zext_ln103_1_fu_288_p1);

assign add_ln113_fu_466_p2 = (sub_ln113_fu_366_p2 + zext_ln113_1_fu_462_p1);

assign and_ln103_fu_320_p2 = (xor_ln103_fu_308_p2 & icmp_ln105_fu_314_p2);

assign and_ln110_1_fu_792_p2 = (or_ln110_2_fu_786_p2 & or_ln110_1_fu_768_p2);

assign and_ln110_2_fu_798_p2 = (grp_fu_869_p_dout0 & and_ln110_1_fu_792_p2);

assign and_ln110_3_fu_880_p2 = (or_ln110_4_fu_874_p2 & or_ln110_3_fu_856_p2);

assign and_ln110_4_fu_886_p2 = (grp_fu_873_p_dout0 & and_ln110_3_fu_880_p2);

assign and_ln110_5_fu_972_p2 = (or_ln110_6_fu_966_p2 & or_ln110_5_fu_948_p2);

assign and_ln110_6_fu_978_p2 = (grp_fu_877_p_dout0 & and_ln110_5_fu_972_p2);

assign and_ln110_fu_708_p2 = (or_ln110_fu_702_p2 & grp_fu_865_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln110_1_fu_722_p1 = layer1_conv_load_1_reg_1062_pp0_iter3_reg;

assign bitcast_ln110_2_fu_739_p1 = select_ln110_reg_1083;

assign bitcast_ln110_3_fu_810_p1 = layer1_conv_load_2_reg_1069_pp0_iter5_reg;

assign bitcast_ln110_4_fu_827_p1 = select_ln110_1_reg_1090_pp0_iter5_reg;

assign bitcast_ln110_5_fu_902_p1 = layer1_conv_load_3_reg_1076_pp0_iter7_reg;

assign bitcast_ln110_6_fu_919_p1 = select_ln110_2_reg_1097_pp0_iter7_reg;

assign bitcast_ln110_fu_673_p1 = layer1_conv_load_reg_1055;

assign empty_fu_229_p2 = (tmp_29_fu_221_p3 | 6'd1);

assign grp_fu_865_p_ce = 1'b1;

assign grp_fu_865_p_din0 = layer1_conv_q3;

assign grp_fu_865_p_din1 = 32'd3463342888;

assign grp_fu_865_p_opcode = 5'd2;

assign grp_fu_869_p_ce = 1'b1;

assign grp_fu_869_p_din0 = layer1_conv_load_1_reg_1062;

assign grp_fu_869_p_din1 = select_ln110_fu_714_p3;

assign grp_fu_869_p_opcode = 5'd2;

assign grp_fu_873_p_ce = 1'b1;

assign grp_fu_873_p_din0 = layer1_conv_load_2_reg_1069_pp0_iter4_reg;

assign grp_fu_873_p_din1 = select_ln110_1_reg_1090;

assign grp_fu_873_p_opcode = 5'd2;

assign grp_fu_877_p_ce = 1'b1;

assign grp_fu_877_p_din0 = layer1_conv_load_3_reg_1076_pp0_iter6_reg;

assign grp_fu_877_p_din1 = select_ln110_2_reg_1097;

assign grp_fu_877_p_opcode = 5'd2;

assign icmp_ln103_fu_235_p2 = ((indvar_flatten39_fu_106 == 12'd3844) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_262_p2 = ((indvar_flatten15_fu_98 == 10'd961) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_314_p2 = ((c_fu_90 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln110_10_fu_936_p2 = ((tmp_10_fu_905_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln110_11_fu_942_p2 = ((trunc_ln110_5_fu_915_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_12_fu_954_p2 = ((tmp_11_fu_922_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln110_13_fu_960_p2 = ((trunc_ln110_6_fu_932_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_1_fu_696_p2 = ((trunc_ln110_fu_686_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_2_fu_756_p2 = ((tmp_5_fu_725_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln110_3_fu_762_p2 = ((trunc_ln110_1_fu_735_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_4_fu_774_p2 = ((tmp_6_fu_742_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln110_5_fu_780_p2 = ((trunc_ln110_2_fu_752_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_6_fu_844_p2 = ((tmp_8_fu_813_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln110_7_fu_850_p2 = ((trunc_ln110_3_fu_823_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_8_fu_862_p2 = ((tmp_9_fu_830_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln110_9_fu_868_p2 = ((trunc_ln110_4_fu_840_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_690_p2 = ((tmp_3_fu_676_p4 != 8'd255) ? 1'b1 : 1'b0);

assign layer1_conv_address0 = zext_ln109_10_fu_623_p1;

assign layer1_conv_address1 = zext_ln109_6_fu_551_p1;

assign layer1_conv_address2 = zext_ln109_8_fu_590_p1;

assign layer1_conv_address3 = zext_ln109_5_fu_522_p1;

assign layer1_pool_address0 = zext_ln113_2_fu_898_p1;

assign layer1_pool_d0 = ((and_ln110_6_fu_978_p2[0:0] == 1'b1) ? layer1_conv_load_3_reg_1076_pp0_iter7_reg : select_ln110_2_reg_1097_pp0_iter7_reg);

assign or_ln104_fu_332_p2 = (icmp_ln104_fu_262_p2 | and_ln103_fu_320_p2);

assign or_ln109_fu_556_p2 = (tmp_34_fu_486_p3 | 6'd1);

assign or_ln110_1_fu_768_p2 = (icmp_ln110_3_fu_762_p2 | icmp_ln110_2_fu_756_p2);

assign or_ln110_2_fu_786_p2 = (icmp_ln110_5_fu_780_p2 | icmp_ln110_4_fu_774_p2);

assign or_ln110_3_fu_856_p2 = (icmp_ln110_7_fu_850_p2 | icmp_ln110_6_fu_844_p2);

assign or_ln110_4_fu_874_p2 = (icmp_ln110_9_fu_868_p2 | icmp_ln110_8_fu_862_p2);

assign or_ln110_5_fu_948_p2 = (icmp_ln110_11_fu_942_p2 | icmp_ln110_10_fu_936_p2);

assign or_ln110_6_fu_966_p2 = (icmp_ln110_13_fu_960_p2 | icmp_ln110_12_fu_954_p2);

assign or_ln110_fu_702_p2 = (icmp_ln110_fu_690_p2 | icmp_ln110_1_fu_696_p2);

assign p_mid113_fu_418_p2 = (p_mid_fu_372_p3 | 6'd1);

assign p_mid_fu_372_p3 = {{add_ln104_fu_326_p2}, {1'd0}};

assign select_ln103_1_fu_276_p3 = ((icmp_ln104_fu_262_p2[0:0] == 1'b1) ? add_ln103_fu_256_p2 : f_fu_102);

assign select_ln103_2_fu_292_p3 = ((icmp_ln104_fu_262_p2[0:0] == 1'b1) ? 6'd0 : tmp_29_fu_221_p3);

assign select_ln103_3_fu_300_p3 = ((icmp_ln104_fu_262_p2[0:0] == 1'b1) ? 6'd1 : empty_fu_229_p2);

assign select_ln103_fu_268_p3 = ((icmp_ln104_fu_262_p2[0:0] == 1'b1) ? 5'd0 : r_1_fu_94);

assign select_ln104_1_fu_346_p3 = ((and_ln103_fu_320_p2[0:0] == 1'b1) ? add_ln104_fu_326_p2 : select_ln103_fu_268_p3);

assign select_ln104_2_fu_380_p3 = ((and_ln103_fu_320_p2[0:0] == 1'b1) ? p_mid_fu_372_p3 : select_ln103_2_fu_292_p3);

assign select_ln104_3_fu_424_p3 = ((and_ln103_fu_320_p2[0:0] == 1'b1) ? p_mid113_fu_418_p2 : select_ln103_3_fu_300_p3);

assign select_ln104_4_fu_640_p3 = ((icmp_ln104_fu_262_p2[0:0] == 1'b1) ? 10'd1 : add_ln104_1_fu_634_p2);

assign select_ln104_fu_338_p3 = ((or_ln104_fu_332_p2[0:0] == 1'b1) ? 5'd0 : c_fu_90);

assign select_ln110_1_fu_804_p3 = ((and_ln110_2_fu_798_p2[0:0] == 1'b1) ? layer1_conv_load_1_reg_1062_pp0_iter3_reg : select_ln110_reg_1083);

assign select_ln110_2_fu_892_p3 = ((and_ln110_4_fu_886_p2[0:0] == 1'b1) ? layer1_conv_load_2_reg_1069_pp0_iter5_reg : select_ln110_1_reg_1090_pp0_iter5_reg);

assign select_ln110_fu_714_p3 = ((and_ln110_fu_708_p2[0:0] == 1'b1) ? layer1_conv_load_reg_1055 : 32'd3463342888);

assign sub_ln109_1_fu_456_p2 = (zext_ln109_2_fu_440_p1 - zext_ln109_3_fu_452_p1);

assign sub_ln109_fu_412_p2 = (zext_ln109_fu_396_p1 - zext_ln109_1_fu_408_p1);

assign sub_ln113_fu_366_p2 = (tmp_fu_358_p3 - zext_ln113_fu_354_p1);

assign tmp_10_fu_905_p4 = {{bitcast_ln110_5_fu_902_p1[30:23]}};

assign tmp_11_fu_922_p4 = {{bitcast_ln110_6_fu_919_p1[30:23]}};

assign tmp_13_fu_388_p3 = {{select_ln104_2_fu_380_p3}, {6'd0}};

assign tmp_14_fu_400_p3 = {{select_ln104_2_fu_380_p3}, {1'd0}};

assign tmp_15_fu_432_p3 = {{select_ln104_3_fu_424_p3}, {6'd0}};

assign tmp_16_fu_444_p3 = {{select_ln104_3_fu_424_p3}, {1'd0}};

assign tmp_29_fu_221_p3 = {{r_1_fu_94}, {1'd0}};

assign tmp_33_fu_472_p3 = {{add_ln113_fu_466_p2}, {2'd0}};

assign tmp_34_fu_486_p3 = {{select_ln104_fu_338_p3}, {1'd0}};

assign tmp_35_fu_514_p3 = {{tmp_40_cast_fu_504_p4}, {select_ln103_1_fu_276_p3}};

assign tmp_36_fu_543_p3 = {{tmp_44_cast_fu_533_p4}, {select_ln103_1_fu_276_p3}};

assign tmp_37_fu_576_p3 = {{add_ln109_2_fu_570_p2}, {2'd0}};

assign tmp_38_fu_609_p3 = {{add_ln109_4_fu_603_p2}, {2'd0}};

assign tmp_3_fu_676_p4 = {{bitcast_ln110_fu_673_p1[30:23]}};

assign tmp_40_cast_fu_504_p4 = {{add_ln109_fu_498_p2[11:1]}};

assign tmp_44_cast_fu_533_p4 = {{add_ln109_1_fu_527_p2[11:1]}};

assign tmp_5_fu_725_p4 = {{bitcast_ln110_1_fu_722_p1[30:23]}};

assign tmp_6_fu_742_p4 = {{bitcast_ln110_2_fu_739_p1[30:23]}};

assign tmp_8_fu_813_p4 = {{bitcast_ln110_3_fu_810_p1[30:23]}};

assign tmp_9_fu_830_p4 = {{bitcast_ln110_4_fu_827_p1[30:23]}};

assign tmp_fu_358_p3 = {{select_ln104_1_fu_346_p3}, {5'd0}};

assign trunc_ln109_1_fu_595_p1 = sub_ln109_1_fu_456_p2[11:0];

assign trunc_ln109_fu_562_p1 = sub_ln109_fu_412_p2[11:0];

assign trunc_ln110_1_fu_735_p1 = bitcast_ln110_1_fu_722_p1[22:0];

assign trunc_ln110_2_fu_752_p1 = bitcast_ln110_2_fu_739_p1[22:0];

assign trunc_ln110_3_fu_823_p1 = bitcast_ln110_3_fu_810_p1[22:0];

assign trunc_ln110_4_fu_840_p1 = bitcast_ln110_4_fu_827_p1[22:0];

assign trunc_ln110_5_fu_915_p1 = bitcast_ln110_5_fu_902_p1[22:0];

assign trunc_ln110_6_fu_932_p1 = bitcast_ln110_6_fu_919_p1[22:0];

assign trunc_ln110_fu_686_p1 = bitcast_ln110_fu_673_p1[22:0];

assign xor_ln103_fu_308_p2 = (icmp_ln104_fu_262_p2 ^ 1'd1);

assign zext_ln103_1_fu_288_p1 = select_ln103_1_fu_276_p3;

assign zext_ln103_fu_284_p1 = select_ln103_1_fu_276_p3;

assign zext_ln109_10_fu_623_p1 = add_ln109_5_fu_617_p2;

assign zext_ln109_1_fu_408_p1 = tmp_14_fu_400_p3;

assign zext_ln109_2_fu_440_p1 = tmp_15_fu_432_p3;

assign zext_ln109_3_fu_452_p1 = tmp_16_fu_444_p3;

assign zext_ln109_4_fu_494_p1 = tmp_34_fu_486_p3;

assign zext_ln109_5_fu_522_p1 = tmp_35_fu_514_p3;

assign zext_ln109_6_fu_551_p1 = tmp_36_fu_543_p3;

assign zext_ln109_7_fu_566_p1 = or_ln109_fu_556_p2;

assign zext_ln109_8_fu_590_p1 = add_ln109_3_fu_584_p2;

assign zext_ln109_9_fu_599_p1 = or_ln109_fu_556_p2;

assign zext_ln109_fu_396_p1 = tmp_13_fu_388_p3;

assign zext_ln113_1_fu_462_p1 = select_ln104_fu_338_p3;

assign zext_ln113_2_fu_898_p1 = add_ln113_1_reg_1030_pp0_iter7_reg;

assign zext_ln113_fu_354_p1 = select_ln104_1_fu_346_p3;

endmodule //cnn_predict_cnn_predict_Pipeline_VITIS_LOOP_103_6_VITIS_LOOP_104_7_VITIS_LOOP_105_8
